export const IMPORTANCE_CONTENT = {
  dashboard: {
    titleId: 'dashboard-importance-title',
    title: 'Why the Operations Dashboard matters',
    closeLabel: 'Close Operations Dashboard explanation',
    beneficiary: 'Retail operations leaders, supply chain analysts, and regional managers',
    builder: 'Analytics engineers and data application developers using familiar SQL',
    lead: 'The business outcome is a shared operating view of demand, inventory, fulfillment risk, spatial context, similarity signals, and AI activity before decisions become escalations.',
    example: 'PeakGear can build a dashboard with converged SQL over product, order, inventory, spatial, graph, vector, and agent data instead of stitching many reports and services together.',
    steps: [
      { title: 'One platform reduces assembly work', body: 'Oracle Autonomous AI Lakehouse keeps operational, analytical, spatial, graph, JSON, vector, and AI-ready data close to the same governed database foundation.' },
      { title: 'Developers use less custom plumbing', body: 'The dashboard can be built with a handful of familiar SQL patterns instead of complex integration pipelines and custom code in another programming stack.' },
      { title: 'Business teams get one answer', body: 'Operations leaders see stock pressure, demand regions, watched products, and AI actions from the same trusted data products.' },
      { title: 'Action happens sooner', body: 'Managers can rebalance inventory, prioritize regions, and escalate capacity issues while there is still time to protect revenue.' },
    ],
    value: 'PeakGear simplifies delivery of an executive operations command center and improves replenishment, allocation, and escalation decisions with one governed AI Lakehouse foundation.',
  },
  webshop: {
    titleId: 'webshop-importance-title',
    title: 'Why AI-powered product discovery matters',
    closeLabel: 'Close webshop search explanation',
    beneficiary: 'Digital commerce leaders, merchandisers, shoppers, and service teams',
    builder: 'Application developers and AI/search engineers reusing governed lakehouse data',
    lead: 'The business outcome is a shopping and service experience that understands intent while staying grounded in trusted product, image, inventory, and order data.',
    example: 'A shopper can describe a use case or upload a product photo, and PeakGear can rank relevant products and support exchanges without copying data into a separate search stack.',
    steps: [
      { title: 'Intent search becomes simpler', body: 'Product attributes, images, embeddings, inventory, and order facts can be served from the same Oracle foundation instead of separate catalog, vector, and service stores.' },
      { title: 'Developers reuse curated data', body: 'The app builder consumes trusted product and inventory data products rather than creating another synchronization path for the webshop.' },
      { title: 'Service actions stay governed', body: 'Order checks, returns guidance, alternatives, and exchange status can reference current Oracle data instead of detached chatbot memory.' },
      { title: 'Experience quality improves', body: 'Merchandisers get better conversion and fewer service dead ends because AI search is connected to real stock, product context, and policies.' },
    ],
    value: 'PeakGear can launch intent-based commerce experiences faster while keeping product discovery, inventory awareness, and service actions governed by the AI Lakehouse.',
  },
  streaming: {
    titleId: 'streaming-importance-title',
    title: 'Why real-time streaming matters',
    closeLabel: 'Close realtime streaming explanation',
    beneficiary: 'Demand planners, category managers, and marketing operations teams',
    builder: 'Streaming engineers and data engineers building live signal pipelines',
    lead: 'The business outcome is earlier awareness of demand shifts, so planning and merchandising teams can react before a batch report confirms the trend.',
    example: 'A trail shoe starts trending in a region, and live social, commerce, and product signals land in Bronze quickly enough to influence allocation and campaign decisions.',
    steps: [
      { title: 'Live signals join governed data', body: 'Streaming events can be captured into the AI Lakehouse beside product, inventory, and regional context instead of remaining in an isolated event system.' },
      { title: 'Pipeline complexity drops', body: 'Builders use GoldenGate Stream Analytics and the same database target pattern instead of building custom consumers, staging stores, and reconciliation jobs.' },
      { title: 'Raw events remain traceable', body: 'Bronze keeps source-shaped events available for audit, replay, Silver standardization, and downstream Gold products.' },
      { title: 'Planning gets faster feedback', body: 'Demand teams can adjust campaigns, allocation, and replenishment while customer interest is still forming.' },
    ],
    value: 'PeakGear reduces the time from market signal to operational response while avoiding a separate real-time analytics architecture for each use case.',
  },
  bronzeLoad: {
    titleId: 'bronze-importance-title',
    title: 'Why Bronze loading matters',
    closeLabel: 'Close Bronze load explanation',
    beneficiary: 'Data stewards, analytics teams, and downstream product owners',
    builder: 'Data engineers and platform teams onboarding source feeds',
    lead: 'The business outcome is faster onboarding of new source data without losing auditability, lineage, or the ability to reprocess from the raw input.',
    example: 'Product, order, inventory, and image manifest extracts land as source-shaped PG tables so PeakGear can inspect what arrived before creating trusted data products.',
    steps: [
      { title: 'Raw data gets a governed landing zone', body: 'Oracle Autonomous AI Lakehouse gives new files a traceable place to land before they are cleaned, joined, or served to applications.' },
      { title: 'Builders avoid one-off ingest paths', body: 'Data Studio provides a repeatable load pattern instead of writing custom file loaders for every business scenario.' },
      { title: 'Source issues stay visible', body: 'Headers, row counts, duplicates, missing values, and source quirks remain inspectable before transformation hides them.' },
      { title: 'Every use case starts from evidence', body: 'Dashboards, AI search, predictions, and agents can all trace back to the same Bronze baseline.' },
    ],
    value: 'PeakGear accelerates source onboarding and reduces data trust issues by standardizing raw intake inside the governed AI Lakehouse.',
  },
  silverProcess: {
    titleId: 'silver-importance-title',
    title: 'Why Silver processing matters',
    closeLabel: 'Close Silver process explanation',
    beneficiary: 'Operations analysts, data product owners, and AI application teams',
    builder: 'Analytics engineers and data engineers creating reusable curated tables',
    lead: 'The business outcome is reusable, trusted data products that can serve dashboards, commerce, machine learning, natural-language access, and agents without redefining metrics each time.',
    example: 'PeakGear standardizes product, order, inventory, image, and demand data once, then reuses those Silver tables across multiple Serve Data and Serve AI demos.',
    steps: [
      { title: 'Rules become shared assets', body: 'Data Transforms captures cleanup, typing, deduplication, and validation rules as reusable processing work instead of hidden logic in each app.' },
      { title: 'Builders reduce downstream rework', body: 'Application and AI builders consume consistent Silver tables rather than repairing raw data independently.' },
      { title: 'Metrics stop drifting', body: 'Business users see the same product, inventory, and demand definitions across dashboards, search, predictions, and agents.' },
      { title: 'Gold delivery speeds up', body: 'Once Silver is trusted, new business outcomes can be assembled from existing data products instead of new integration projects.' },
    ],
    value: 'PeakGear reduces duplicate transformation effort and speeds up delivery of governed use cases across the AI Lakehouse.',
  },
  icebergCatalogServer: {
    titleId: 'iceberg-catalog-server-importance-title',
    title: 'Why an Iceberg catalog server matters',
    closeLabel: 'Close Iceberg catalog server explanation',
    beneficiary: 'Data engineers, analytics teams, and AI application builders using shared Iceberg data',
    builder: 'Platform engineers configuring Data Transforms and governed lakehouse storage',
    lead: 'The business outcome is a governed, reusable catalog for Iceberg tables so data products can be discovered and processed consistently instead of being configured separately in each tool.',
    example: 'PeakGear can register its Iceberg REST catalog once, then use Data Transforms to discover and build curated data products on the same OCI object storage tables.',
    steps: [
      { title: 'Table discovery becomes shared', body: 'A catalog gives Data Transforms one consistent view of Iceberg namespaces and tables instead of requiring manual storage-path setup for every flow.' },
      { title: 'Storage credentials stay reusable', body: 'The configured OCI access values let the Data Transforms catalog connection reach the same object storage used by the lakehouse.' },
      { title: 'Interoperability improves', body: 'Iceberg tables can be consumed by compatible processing engines while the catalog preserves the metadata contract that describes them.' },
      { title: 'New pipelines start faster', body: 'Once the catalog server is registered, builders can focus on transformation logic rather than rebuilding connectivity for each pipeline.' },
    ],
    value: 'PeakGear makes Iceberg data products easier to discover, govern, and reuse across Data Transforms and compatible lakehouse workloads.',
  },
  productCatalog: {
    titleId: 'catalog-importance-title',
    title: 'Why the Product Catalog matters',
    closeLabel: 'Close Product Catalog explanation',
    beneficiary: 'Merchandising leaders, catalog owners, store teams, and digital commerce teams',
    builder: 'Data product owners and application developers publishing trusted product context',
    lead: 'The business outcome is a single product backbone that keeps merchandising, operations, commerce, and AI experiences aligned on the same SKU truth.',
    example: 'A single product record can connect catalog attributes, inventory, orders, demand signals, images, and vector similarity without duplicating the product model across systems.',
    steps: [
      { title: 'Product truth becomes reusable', body: 'The AI Lakehouse makes curated product data a shared data product for dashboards, search, fulfillment, ML, and agents.' },
      { title: 'Builders avoid catalog copies', body: 'Teams do not need separate product extracts for reporting, search, inventory apps, and AI prototypes.' },
      { title: 'Converged context improves decisions', body: 'Relational attributes, images, demand, inventory, and embeddings can be joined through Oracle instead of synchronized through custom services.' },
      { title: 'Business teams speak one language', body: 'Merchandising and operations teams can compare performance and availability without mismatched identifiers or category definitions.' },
    ],
    value: 'PeakGear creates a governed product backbone that simplifies new Serve Data and Serve AI use cases built on product context.',
  },
  socialFeed: {
    titleId: 'social-importance-title',
    title: 'Why Retail Demand Sensing matters',
    closeLabel: 'Close Retail Demand Sensing explanation',
    beneficiary: 'Demand planners, category managers, and marketing teams',
    builder: 'Analytics engineers and AI engineers turning noisy signals into product-linked insight',
    lead: 'The business outcome is earlier category action from weak demand signals that would otherwise remain noisy, disconnected, or too late for planning.',
    example: 'PeakGear can search social and commerce signals semantically, connect them to products and regions, and prioritize replenishment or campaigns around real customer momentum.',
    steps: [
      { title: 'Signals gain business context', body: 'Vector search, product data, regional context, and inventory can work together in Oracle instead of separate social listening and reporting tools.' },
      { title: 'Builders need fewer moving parts', body: 'The use case can combine semantic search and SQL over governed data without exporting signals into a custom AI pipeline.' },
      { title: 'Planners see why it matters', body: 'A high-signal post becomes actionable only when it connects to SKU, category, region, and stock readiness.' },
      { title: 'Category decisions move earlier', body: 'Teams can tune campaigns, allocations, and replenishment before the demand shift appears in historical sales reports.' },
    ],
    value: 'PeakGear turns noisy demand signals into governed product intelligence and reduces the engineering needed to operationalize trend sensing.',
  },
  returnsGraph: {
    titleId: 'graph-importance-title',
    title: 'Why the Returns Risk Network matters',
    closeLabel: 'Close Returns Risk Network explanation',
    beneficiary: 'Fraud analysts, returns operations managers, and loss-prevention teams',
    builder: 'Data application developers and analysts using SQL/PGQ over governed transaction data',
    lead: 'The business outcome is faster identification of suspicious connected behavior without moving transaction data into a separate graph platform.',
    example: 'A suspicious return can expand into linked customers, orders, stores, refund methods, and repeated patterns while the governed Oracle data remains the source of truth.',
    steps: [
      { title: 'Relationship risk stays close to transactions', body: 'Oracle Graph lets builders analyze connected behavior where order and customer data already lives.' },
      { title: 'Developers avoid graph duplication', body: 'SQL/PGQ supports graph-style questions without copying rows into a separate graph database and synchronizing it back.' },
      { title: 'Analysts find patterns faster', body: 'The network view exposes shared accounts, stores, receipts, and refund behavior that table-by-table review can miss.' },
      { title: 'Escalations become more precise', body: 'Operations can focus on coordinated return patterns instead of treating every unusual transaction as equal risk.' },
    ],
    value: 'PeakGear shortens return-risk investigations and simplifies graph analytics by using converged database capabilities in the AI Lakehouse.',
  },
  fulfillmentMap: {
    titleId: 'fulfillment-importance-title',
    title: 'Why the Store Fulfillment Map matters',
    closeLabel: 'Close Store Fulfillment Map explanation',
    beneficiary: 'Fulfillment managers, regional operations leads, and service-level owners',
    builder: 'Spatial application developers and analytics engineers using Oracle Spatial with operational data',
    lead: 'The business outcome is better fulfillment reliability because location, stock, service zones, demand, routes, and customer priority are evaluated together.',
    example: 'PeakGear can compare store and DC capacity, customer tiers, route geometry, service zones, demand regions, and alerts in one map without a separate GIS data mart.',
    steps: [
      { title: 'Location becomes operational data', body: 'Oracle Spatial keeps geography, service zones, and proximity logic inside the same foundation as inventory and customer data.' },
      { title: 'Builders skip GIS synchronization', body: 'The map can query spatial and relational data together instead of building custom integrations between a database, GIS server, and reporting layer.' },
      { title: 'Managers see real constraints', body: 'A site with stock may still be wrong if it is outside the zone, far from the customer, or already under capacity pressure.' },
      { title: 'Regional response improves', body: 'Teams can rebalance transfers, reduce late fulfillment, and detect overloaded sites before service levels degrade.' },
    ],
    value: 'PeakGear improves fulfillment reliability and reduces location-analytics complexity by serving spatial decisions from the AI Lakehouse.',
  },
  orders: {
    titleId: 'orders-importance-title',
    title: 'Why Orders & Fulfillment Flow matters',
    closeLabel: 'Close Orders & Fulfillment Flow explanation',
    beneficiary: 'Order operations owners, service teams, and digital channel leaders',
    builder: 'Application developers building API-friendly order experiences',
    lead: 'The business outcome is faster delivery of order experiences that need both transaction integrity and document-shaped API access.',
    example: 'The same order can be queried as normalized relational rows or served as a nested JSON document, with no sync lag and no copy into a separate document database.',
    steps: [
      { title: 'Apps get document shape without data copies', body: 'JSON Relational Duality exposes app-friendly JSON over the same Oracle rows that preserve transactional consistency.' },
      { title: 'Developers avoid dual persistence', body: 'Builders do not need to maintain one relational store for operations and another document store for APIs.' },
      { title: 'Security remains attached', body: 'Row-level controls and governed access stay with the data regardless of whether the app reads relational rows or JSON documents.' },
      { title: 'Operations stay current', body: 'Order, item, customer, inventory, and fulfillment status changes are visible without reconciliation lag.' },
    ],
    value: 'PeakGear can build order APIs and operational flows faster while preserving ACID consistency, governed access, and zero-copy JSON access.',
  },
  oml: {
    titleId: 'oml-importance-title',
    title: 'Why Demand, Revenue & Inventory Predictions matter',
    closeLabel: 'Close Machine Learning explanation',
    beneficiary: 'Demand planners, finance analysts, inventory planners, and category leaders',
    builder: 'ML engineers, data scientists, and analytics engineers training models on governed data',
    lead: 'The business outcome is forward-looking planning from trusted operational data without creating a disconnected feature pipeline.',
    example: 'PeakGear can score demand risk, segment customers, forecast revenue, cluster products, and flag capacity pressure from the same Oracle data foundation used by operations.',
    steps: [
      { title: 'Models use governed features', body: 'Oracle Machine Learning works close to curated lakehouse tables so model inputs use the same definitions as dashboards and apps.' },
      { title: 'Builders reduce data movement', body: 'ML teams do not need to export stale extracts into a separate stack just to train, score, and operationalize predictions.' },
      { title: 'Predictions become usable faster', body: 'Forecasts and risk scores can feed inventory, fulfillment, campaigns, and agents through the same database foundation.' },
      { title: 'Business users trust the output', body: 'Lineage back to curated tables helps planners understand which data drove the forecast or risk signal.' },
    ],
    value: 'PeakGear turns governed lakehouse data into operational predictions while reducing ML integration, feature drift, and reconciliation work.',
  },
  askData: {
    titleId: 'askdata-importance-title',
    title: 'Why Ask Your Data matters',
    closeLabel: 'Close Ask Your Data explanation',
    beneficiary: 'Business analysts, operations analysts, and managers who need quick answers',
    builder: 'Analytics engineers and AI engineers enabling natural-language access to governed SQL',
    lead: 'The business outcome is faster self-service insight while keeping answers grounded in live governed data and inspectable SQL.',
    example: 'A user can ask about top categories, inventory, demand, or order trends and review the SQL that Oracle executes instead of waiting for another report.',
    steps: [
      { title: 'Questions stay in business language', body: 'Managers can ask for the decision they need without first knowing the schema or exact SQL syntax.' },
      { title: 'SQL remains the control point', body: 'Select AI or the local runtime can draft SQL, while Oracle executes against governed live data rather than an opaque copy.' },
      { title: 'Builders avoid report sprawl', body: 'Analytics teams can expose conversational access to trusted data instead of creating a new dashboard for every follow-up question.' },
      { title: 'Trust stays visible', body: 'Inspectable SQL makes the AI answer explainable to analysts and easier to validate against known metrics.' },
    ],
    value: 'PeakGear shortens insight cycles and simplifies self-service analytics by combining natural language with governed SQL execution in the AI Lakehouse.',
  },
  agents: {
    titleId: 'agents-importance-title',
    title: 'Why Retail Operations Agents matter',
    closeLabel: 'Close Retail Operations Agents explanation',
    beneficiary: 'Operations supervisors, service leads, and merchandising teams',
    builder: 'AI engineers and application developers building tool-using agents on live data',
    lead: 'The business outcome is AI assistance that can reason over current facts, call approved tools, and leave an auditable decision trail.',
    example: 'Agent teams can analyze demand signals, check inventory, route fulfillment work, and log decisions back to Oracle instead of producing only free-form recommendations.',
    steps: [
      { title: 'Agents need governed context', body: 'Operational advice is useful only when it reads current product, order, inventory, fulfillment, and demand data.' },
      { title: 'Builders reuse the same foundation', body: 'AI engineers can connect tools to existing Oracle data products instead of creating a separate agent data layer for every workflow.' },
      { title: 'Actions become auditable', body: 'Tool calls and recommendations written back to Oracle give supervisors a durable record for review and follow-up.' },
      { title: 'Teams reduce handoffs', body: 'Trend, fulfillment, and commerce agents can coordinate across the same governed data instead of passing work through disconnected applications.' },
    ],
    value: 'PeakGear can automate operational recommendations while keeping AI context, tool execution, and decision history governed by the AI Lakehouse.',
  },
  customerCdc: {
    titleId: 'cdc-importance-title',
    title: 'Why Change Data Capture matters',
    closeLabel: 'Close Change Data Capture explanation',
    beneficiary: 'Customer operations, marketing, service, and analytics teams',
    builder: 'Integration architects and data platform engineers using GoldenGate',
    lead: 'The business outcome is current customer context in the lakehouse without waiting for nightly batch loads or manually reconciling source-system changes.',
    example: 'A new NetSuite customer is inserted in the source table, and GoldenGate applies the change into the ADB Bronze customer mirror for immediate downstream use.',
    steps: [
      { title: 'Operational changes stay fresh', body: 'New customers, loyalty tiers, and contact updates can reach the AI Lakehouse while the source system remains the system of record.' },
      { title: 'Builders avoid batch handoffs', body: 'GoldenGate CDC replaces custom extract jobs, file drops, and reconciliation scripts for incremental customer changes.' },
      { title: 'Use cases share current data', body: 'Segmentation, service workflows, analytics, and AI experiences can all consume the same synchronized customer mirror.' },
      { title: 'Latency becomes a business advantage', body: 'Teams can respond to customer changes quickly instead of discovering them after the next load window.' },
    ],
    value: 'PeakGear reduces customer-data latency and integration complexity by streaming operational changes into the AI Lakehouse.',
  },
  lakehouseConfig: {
    titleId: 'lakehouse-config-importance-title',
    title: 'Why LiveStack Configuration matters',
    closeLabel: 'Close LiveStack Configuration explanation',
    beneficiary: 'Workshop facilitators, platform owners, and demo participants',
    builder: 'Platform engineers and solution architects validating the shared runtime foundation',
    lead: 'The business outcome is confidence that every demo depends on the same connected AI Lakehouse foundation before users start exploring outcomes.',
    example: 'The page validates ADB, GoldenGate Stream Analytics, OCI GenAI, demo data, DB Actions targets, and seeded PG credentials in one place.',
    steps: [
      { title: 'Readiness is part of the story', body: 'The demos only make sense when database, data, AI, streaming, and tool links are connected as one working foundation.' },
      { title: 'Builders troubleshoot once', body: 'Platform owners can validate shared dependencies centrally instead of chasing failures page by page.' },
      { title: 'Users see foundation health', body: 'Green-light checks explain which part of the AI Lakehouse is ready and which dependency needs attention.' },
      { title: 'Demos become repeatable', body: 'Seed, validate, refresh, and credential actions reduce the operational complexity of running the full LiveStack.' },
    ],
    value: 'PeakGear makes the AI Lakehouse foundation observable and repeatable, reducing setup risk before business users evaluate the use cases.',
  },
};
