#!/usr/bin/env bash

set -Eeuo pipefail

log() {
  printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*"
}

xml_escape() {
  local value="$1"
  value="${value//&/&amp;}"
  value="${value//</&lt;}"
  value="${value//>/&gt;}"
  value="${value//\"/&quot;}"
  value="${value//\'/&apos;}"
  printf '%s' "$value"
}

xml_unescape() {
  local value="$1"
  value="${value//&lt;/<}"
  value="${value//&gt;/>}"
  value="${value//&quot;/\"}"
  value="${value//&apos;/\'}"
  value="${value//&amp;/&}"
  printf '%s' "$value"
}

xml_set_value() {
  local xml_file="$1"
  local set_name="$2"

  sed -n "s|.*<Set name=\"${set_name}\">\\(.*\\)</Set>.*|\\1|p" "${xml_file}" | head -n 1
}

xml_datasource_class() {
  local xml_file="$1"

  awk '
    /<Arg>jdbc\/OSADataSource<\/Arg>/ { in_datasource = 1; next }
    in_datasource && match($0, /class="([^"]+)"/, m) { print m[1]; exit }
  ' "${xml_file}"
}

sed_escape_replacement() {
  printf '%s' "$1" | sed -e 's/[&|\\]/\\&/g'
}

sync_helidon_datasource_from_xml() {
  local xml_file="$1"
  shift

  local ds_class ds_url ds_user ds_password
  ds_class="$(xml_datasource_class "${xml_file}")"
  ds_url="$(xml_unescape "$(xml_set_value "${xml_file}" "URL")")"
  ds_user="$(xml_unescape "$(xml_set_value "${xml_file}" "User")")"
  ds_password="$(xml_unescape "$(xml_set_value "${xml_file}" "Password")")"

  if [[ -z "${ds_class}" || -z "${ds_url}" || -z "${ds_user}" || -z "${ds_password}" ]]; then
    log "Could not fully derive Helidon datasource settings from ${xml_file}"
    exit 1
  fi

  ds_class="$(sed_escape_replacement "${ds_class}")"
  ds_url="$(sed_escape_replacement "${ds_url}")"
  ds_user="$(sed_escape_replacement "${ds_user}")"
  ds_password="$(sed_escape_replacement "${ds_password}")"

  local yaml_file
  for yaml_file in "$@"; do
    [[ -f "${yaml_file}" ]] || continue
    sed -i "s|^\(\s*connectionFactoryClassName:\).*|\1 ${ds_class}|" "${yaml_file}"
    sed -i "s|^\(\s*url:\).*|\1 ${ds_url}|" "${yaml_file}"
    sed -i "s|^\(\s*user:\).*|\1 ${ds_user}|" "${yaml_file}"
    sed -i "s|^\(\s*password:\).*|\1 ${ds_password}|" "${yaml_file}"
  done
}

sql_escape() {
  printf "%s" "$1" | sed "s/'/''/g"
}

mysql_cli_args() {
  local -n out_ref=$1
  out_ref=(mysql --protocol=socket --socket="${MYSQL_SOCKET}" -u"${MYSQL_ROOT_USER}")
  if [[ -n "${MYSQL_ROOT_PASSWORD}" ]]; then
    out_ref+=(-p"${MYSQL_ROOT_PASSWORD}")
  fi
}

mysqladmin_args() {
  local -n out_ref=$1
  out_ref=(mysqladmin --protocol=socket --socket="${MYSQL_SOCKET}" -u"${MYSQL_ROOT_USER}")
  if [[ -n "${MYSQL_ROOT_PASSWORD}" ]]; then
    out_ref+=(-p"${MYSQL_ROOT_PASSWORD}")
  fi
}

require_env() {
  local name="$1"
  if [[ -z "${!name:-}" ]]; then
    log "Required environment variable ${name} is empty"
    exit 1
  fi
}

is_truthy() {
  local value="${1:-}"
  value="${value,,}"
  case "${value}" in
    1|true|yes|y|on)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

is_auto_public_host() {
  local value="${1:-}"
  value="${value,,}"
  case "${value}" in
    ""|auto|localhost|127.0.0.1|0.0.0.0)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

detect_public_host() {
  local host=""

  host="$(
    curl -fsS --connect-timeout 2 --max-time 5 \
      -H "Authorization: Bearer Oracle" \
      http://169.254.169.254/opc/v2/vnics/ 2>/dev/null \
      | awk -F'"' '/"publicIp"[[:space:]]*:/ && $4 != "" { print $4; exit }' || true
  )"
  if [[ -n "${host}" ]]; then
    printf '%s\n' "${host}"
    return 0
  fi

  local endpoint
  for endpoint in \
    https://api.ipify.org \
    https://ifconfig.me/ip \
    https://checkip.amazonaws.com
  do
    host="$(curl -fsS --connect-timeout 3 --max-time 8 "${endpoint}" 2>/dev/null | tr -d '[:space:]' || true)"
    if [[ -n "${host}" ]]; then
      printf '%s\n' "${host}"
      return 0
    fi
  done

  hostname -I 2>/dev/null | awk '{ print $1 }'
}

persist_public_host_env() {
  local env_file="/etc/ggsa-public-host.env"
  local profile_file="/etc/profile.d/ggsa-public-host.sh"

  cat > "${env_file}" <<EOF
HOST=${GGSA_PUBLIC_HOST}
PUBLISH_HOST=${PUBLISH_HOST}
GGSA_PUBLIC_HOST=${GGSA_PUBLIC_HOST}
OSA_PUBLIC_HOST=${OSA_PUBLIC_HOST}
SPARK_PUBLIC_DNS=${SPARK_PUBLIC_DNS}
KAFKA_ADVERTISED_LISTENERS=${KAFKA_ADVERTISED_LISTENERS}
EOF

  cat > "${profile_file}" <<EOF
# Generated by ggsa-entrypoint.sh at container startup.
export HOST='${GGSA_PUBLIC_HOST}'
export PUBLISH_HOST='${PUBLISH_HOST}'
export GGSA_PUBLIC_HOST='${GGSA_PUBLIC_HOST}'
export OSA_PUBLIC_HOST='${OSA_PUBLIC_HOST}'
export SPARK_PUBLIC_DNS='${SPARK_PUBLIC_DNS}'
export KAFKA_ADVERTISED_LISTENERS='${KAFKA_ADVERTISED_LISTENERS}'
EOF
}

configure_public_host() {
  local public_host listener_host

  if ! is_auto_public_host "${GGSA_PUBLIC_HOST:-}"; then
    public_host="${GGSA_PUBLIC_HOST}"
  elif ! is_auto_public_host "${PUBLISH_HOST:-}"; then
    public_host="${PUBLISH_HOST}"
  elif ! is_auto_public_host "${OSA_PUBLIC_HOST:-}"; then
    public_host="${OSA_PUBLIC_HOST}"
  else
    public_host="$(detect_public_host)"
  fi

  if [[ -z "${public_host}" ]]; then
    log "Could not determine the public host for GGSA; pass GGSA_PUBLIC_HOST or PUBLISH_HOST explicitly"
    exit 1
  fi

  case "${public_host}" in
    *[!A-Za-z0-9.:-]*)
      log "Refusing invalid public host value: ${public_host}"
      exit 1
      ;;
  esac

  export PUBLISH_HOST="${public_host}"
  export GGSA_PUBLIC_HOST="${public_host}"
  export OSA_PUBLIC_HOST="${public_host}"

  if is_auto_public_host "${SPARK_PUBLIC_DNS:-}"; then
    export SPARK_PUBLIC_DNS="${public_host}"
  fi

  listener_host="${KAFKA_ADVERTISED_LISTENERS#PLAINTEXT://}"
  listener_host="${listener_host%%:*}"
  if is_auto_public_host "${KAFKA_ADVERTISED_LISTENERS:-}" || is_auto_public_host "${listener_host}"; then
    export KAFKA_ADVERTISED_LISTENERS="PLAINTEXT://${public_host}:${KAFKA_BROKER_PORT}"
  fi

  export HOST="${public_host}"
  persist_public_host_env

  log "Using public host ${public_host} for OSA, Spark, and Kafka advertised endpoints"
}

generate_osa_secured_password() {
  local plaintext_password="$1"
  local output secured_password

  output="$(
    cd "${OSA_BASE}/bin"
    ./osa-secure-tool.sh "${plaintext_password}" 2>&1
  )" || {
    log "Failed to generate the OSA secured password"
    printf '%s\n' "${output}" >&2
    exit 1
  }

  secured_password="$(printf '%s\n' "${output}" | sed -n 's/^OSA Secured Password = //p' | tail -n 1)"
  if [[ -z "${secured_password}" ]]; then
    log "Could not parse the OSA secured password from osa-secure-tool.sh output"
    printf '%s\n' "${output}" >&2
    exit 1
  fi

  printf '%s' "${secured_password}"
}

generate_osa_self_signed_certificate() {
  local certificate_password="$1"
  local ssl_dir="${OSA_RUNTIME_DIR}/ssl"
  local certificate_dir="${OSA_BASE}/certificate"
  local subject cn p12_path key_path crt_path

  cn="${OSA_SSL_CERT_CN:-${OSA_PUBLIC_HOST}}"
  subject="${OSA_SSL_CERT_SUBJECT:-/CN=${cn}/OU=GoldenGate/O=Oracle/L=Redwood Shores/ST=CA/C=US}"
  p12_path="${ssl_dir}/self-server.p12"
  key_path="${ssl_dir}/self-server.key"
  crt_path="${ssl_dir}/self-server.crt"

  mkdir -p "${ssl_dir}" "${certificate_dir}"

  if [[ ! -f "${p12_path}" ]]; then
    log "Generating self-signed OSA TLS certificate" >&2
    openssl req -x509 -newkey rsa:3072 \
      -keyout "${key_path}" \
      -out "${crt_path}" \
      -days "${OSA_SSL_CERT_VALID_DAYS:-3650}" \
      -subj "${subject}" \
      -nodes \
      -sha256 >/dev/null 2>&1 || {
        log "Failed to generate the self-signed TLS certificate"
        exit 1
      }

    openssl pkcs12 -export \
      -out "${p12_path}" \
      -inkey "${key_path}" \
      -in "${crt_path}" \
      -passout pass:"${certificate_password}" >/dev/null 2>&1 || {
        log "Failed to package the self-signed TLS certificate as PKCS#12"
        exit 1
      }
  fi

  if [[ -f "${crt_path}" ]]; then
    cp -f "${crt_path}" "${certificate_dir}/ca.pem"
  fi

  printf '%s' "${p12_path}"
}

render_mysql_cnf() {
  cat > /etc/my.cnf.d/ggsa.cnf <<EOF
[mysqld]
bind-address=0.0.0.0
datadir=${MYSQL_DATADIR}
socket=${MYSQL_SOCKET}
pid-file=${MYSQL_PID_FILE}
port=${MYSQL_TCP_PORT}
skip-name-resolve=ON
log-error=/var/log/mysql/error.log
EOF
}

mysql_password_marker() {
  printf '%s/.ll-lakehouse-mysql-password.sha256' "${MYSQL_DATADIR}"
}

mysql_password_hash() {
  printf '%s' "${MYSQL_ROOT_PASSWORD}" | sha256sum | awk '{print $1}'
}

write_mysql_password_marker() {
  local marker
  marker="$(mysql_password_marker)"
  mysql_password_hash > "${marker}"
  chown mysql:mysql "${marker}"
  chmod 600 "${marker}"
}

clear_mysql_runtime_files() {
  rm -f \
    "${MYSQL_SOCKET}" \
    "${MYSQL_SOCKET}.lock" \
    "${MYSQL_PID_FILE}" \
    /var/run/mysqld/mysqlx.sock \
    /var/run/mysqld/mysqlx.sock.lock
}

reset_mysql_datadir_for_password_change() {
  if ! is_truthy "${GGSA_RESET_MYSQL_ON_PASSWORD_CHANGE:-true}"; then
    log "GGSA MySQL password changed, but reset is disabled"
    return 1
  fi

  if [[ -z "${MYSQL_DATADIR}" || "${MYSQL_DATADIR}" == "/" ]]; then
    log "Refusing to reset unsafe MySQL data directory: ${MYSQL_DATADIR:-<empty>}"
    return 1
  fi

  log "Resetting GGSA MySQL metadata because the deployment password changed"
  find "${MYSQL_DATADIR}" -mindepth 1 -maxdepth 1 -exec rm -rf -- {} +
  mkdir -p "${MYSQL_DATADIR}"
  chown -R mysql:mysql "${MYSQL_DATADIR}"
}

prepare_mysql_datadir_for_current_password() {
  local marker current_hash stored_hash

  if [[ ! -d "${MYSQL_DATADIR}/mysql" ]]; then
    return 0
  fi

  marker="$(mysql_password_marker)"
  if [[ ! -f "${marker}" ]]; then
    log "GGSA MySQL password marker is missing; validating the existing volume with the current deployment password"
    return 0
  fi

  current_hash="$(mysql_password_hash)"
  stored_hash="$(cat "${marker}" 2>/dev/null || true)"
  if [[ "${stored_hash}" == "${current_hash}" ]]; then
    return 0
  fi

  reset_mysql_datadir_for_password_change
}

initialize_mysql_datadir() {
  mkdir -p "${MYSQL_DATADIR}" /var/run/mysqld /var/log/mysql
  chown -R mysql:mysql "${MYSQL_DATADIR}" /var/run/mysqld /var/log/mysql
  clear_mysql_runtime_files
  prepare_mysql_datadir_for_current_password

  if [[ ! -d "${MYSQL_DATADIR}/mysql" ]]; then
    log "Initializing MySQL data directory"
    mysqld --initialize-insecure --user=mysql --datadir="${MYSQL_DATADIR}"
    MYSQL_FIRST_BOOT=true
  else
    MYSQL_FIRST_BOOT=false
  fi
}

stop_mysql_if_running() {
  if pgrep -x mysqld >/dev/null 2>&1; then
    local mysql_admin=()
    mysqladmin_args mysql_admin
    "${mysql_admin[@]}" shutdown >/dev/null 2>&1 || true
    sleep 2
  fi
  pkill -x mysqld >/dev/null 2>&1 || true
  clear_mysql_runtime_files
}

wait_for_mysql() {
  local timeout="${MYSQL_READY_TIMEOUT:-120}"
  local start_time=$SECONDS

  while (( SECONDS - start_time < timeout )); do
    if mysqladmin --protocol=socket --socket="${MYSQL_SOCKET}" -u"${MYSQL_ROOT_USER}" ping >/dev/null 2>&1; then
      return 0
    fi
    if [[ -n "${MYSQL_ROOT_PASSWORD}" ]] && mysqladmin --protocol=socket --socket="${MYSQL_SOCKET}" -u"${MYSQL_ROOT_USER}" -p"${MYSQL_ROOT_PASSWORD}" ping >/dev/null 2>&1; then
      return 0
    fi
    sleep 2
  done

  log "MySQL did not become ready within ${timeout} seconds"
  exit 1
}

configure_mysql() {
  local db_name escaped_root_password escaped_mysql_user escaped_mysql_password
  db_name="${MYSQL_DATABASE//\`/}"
  escaped_root_password="$(sql_escape "${MYSQL_ROOT_PASSWORD}")"
  escaped_mysql_user="$(sql_escape "${MYSQL_USER}")"
  escaped_mysql_password="$(sql_escape "${MYSQL_PASSWORD}")"

  if [[ "${MYSQL_FIRST_BOOT}" == "true" ]]; then
    log "Configuring MySQL root password and OSA schema"
    mysql --protocol=socket --socket="${MYSQL_SOCKET}" -u"${MYSQL_ROOT_USER}" <<SQL
ALTER USER '${MYSQL_ROOT_USER}'@'localhost' IDENTIFIED BY '${escaped_root_password}';
CREATE DATABASE IF NOT EXISTS \`${db_name}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${escaped_mysql_user}'@'localhost' IDENTIFIED BY '${escaped_mysql_password}';
CREATE USER IF NOT EXISTS '${escaped_mysql_user}'@'%' IDENTIFIED BY '${escaped_mysql_password}';
GRANT ALL PRIVILEGES ON \`${db_name}\`.* TO '${escaped_mysql_user}'@'localhost';
GRANT ALL PRIVILEGES ON \`${db_name}\`.* TO '${escaped_mysql_user}'@'%';
FLUSH PRIVILEGES;
SQL
  fi

  local mysql_cli=()
  mysql_cli_args mysql_cli

  "${mysql_cli[@]}" <<SQL
CREATE DATABASE IF NOT EXISTS \`${db_name}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${escaped_mysql_user}'@'localhost' IDENTIFIED BY '${escaped_mysql_password}';
CREATE USER IF NOT EXISTS '${escaped_mysql_user}'@'%' IDENTIFIED BY '${escaped_mysql_password}';
ALTER USER '${escaped_mysql_user}'@'localhost' IDENTIFIED BY '${escaped_mysql_password}';
ALTER USER '${escaped_mysql_user}'@'%' IDENTIFIED BY '${escaped_mysql_password}';
GRANT ALL PRIVILEGES ON \`${db_name}\`.* TO '${escaped_mysql_user}'@'localhost';
GRANT ALL PRIVILEGES ON \`${db_name}\`.* TO '${escaped_mysql_user}'@'%';
FLUSH PRIVILEGES;
SQL

  local schema_exists
  schema_exists="$("${mysql_cli[@]}" -Nse "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='$(sql_escape "${db_name}")' AND table_name='osa_system_property';")"
  if [[ "${schema_exists}" == "0" ]]; then
    log "Seeding OSA MySQL schema"
    "${mysql_cli[@]}" "${db_name}" < "${OSA_BASE}/sql/seedMysqlSchema.sql"
  fi

  local admin_hash escaped_admin_user
  admin_hash="MD5:$(printf '%s' "${OSA_ADMIN_PASSWORD}" | md5sum | awk '{print $1}')"
  escaped_admin_user="$(sql_escape "${OSA_ADMIN_USER}")"

  "${mysql_cli[@]}" "${db_name}" <<SQL
INSERT INTO osa_users (id, username, pwd)
VALUES (1, '${escaped_admin_user}', '${admin_hash}')
ON DUPLICATE KEY UPDATE username=VALUES(username), pwd=VALUES(pwd);
INSERT IGNORE INTO osa_roles (id, role) VALUES (1, 'admin');
INSERT IGNORE INTO osa_user_roles (user_id, role_id) VALUES (1, 1);
SQL

  write_mysql_password_marker
}

start_mysql() {
  render_mysql_cnf
  initialize_mysql_datadir

  log "Starting MySQL"
  mysqld --user=mysql --daemonize
  wait_for_mysql
  if ! configure_mysql; then
    log "MySQL configuration failed with the current deployment password"
    if [[ "${MYSQL_FIRST_BOOT}" == "false" ]] && [[ ! -f "$(mysql_password_marker)" ]]; then
      log "Existing GGSA MySQL volume has no password marker; treating it as stale"
      stop_mysql_if_running
      reset_mysql_datadir_for_password_change
      initialize_mysql_datadir
      log "Starting MySQL after GGSA metadata reset"
      mysqld --user=mysql --daemonize
      wait_for_mysql
      configure_mysql
    else
      return 1
    fi
  fi
}

render_kafka_config() {
  cat > /etc/kafka/server.properties <<EOF
process.roles=broker,controller
node.id=1
controller.quorum.voters=1@localhost:${KAFKA_CONTROLLER_PORT}
controller.listener.names=CONTROLLER
listeners=INTERNAL://127.0.0.1:${KAFKA_INTERNAL_BROKER_PORT},PLAINTEXT://0.0.0.0:${KAFKA_BROKER_PORT},CONTROLLER://0.0.0.0:${KAFKA_CONTROLLER_PORT}
advertised.listeners=INTERNAL://localhost:${KAFKA_INTERNAL_BROKER_PORT},${KAFKA_ADVERTISED_LISTENERS}
listener.security.protocol.map=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
inter.broker.listener.name=INTERNAL
num.partitions=3
offsets.topic.replication.factor=1
transaction.state.log.replication.factor=1
transaction.state.log.min.isr=1
group.initial.rebalance.delay.ms=0
log.dirs=/var/lib/kafka/data
auto.create.topics.enable=true
EOF
}

start_kafka() {
  render_kafka_config
  mkdir -p /var/lib/kafka/data /var/log/kafka

  local cluster_id
  if [[ -f /var/lib/kafka/cluster.id ]]; then
    cluster_id="$(< /var/lib/kafka/cluster.id)"
  elif [[ -f /var/lib/kafka/data/meta.properties ]]; then
    cluster_id="$(awk -F= '$1=="cluster.id"{print $2}' /var/lib/kafka/data/meta.properties | tail -n1)"
    if [[ -n "${cluster_id}" ]]; then
      printf '%s\n' "${cluster_id}" > /var/lib/kafka/cluster.id
    fi
  else
    cluster_id="$("${KAFKA_HOME}/bin/kafka-storage.sh" random-uuid)"
    printf '%s\n' "${cluster_id}" > /var/lib/kafka/cluster.id
  fi

  log "Formatting Kafka KRaft storage"
  "${KAFKA_HOME}/bin/kafka-storage.sh" format --ignore-formatted --cluster-id "${cluster_id}" --config /etc/kafka/server.properties >/dev/null

  log "Starting Kafka"
  KAFKA_PID_FILE=/var/lib/kafka/kafka.pid "${KAFKA_HOME}/bin/kafka-server-start.sh" -daemon /etc/kafka/server.properties

  local timeout="${KAFKA_READY_TIMEOUT:-120}"
  local start_time=$SECONDS
  while (( SECONDS - start_time < timeout )); do
    if kafka_is_ready; then
      return 0
    fi
    sleep 2
  done

  log "Kafka did not become ready within ${timeout} seconds"
  exit 1
}

kafka_is_ready() {
  "${KAFKA_HOME}/bin/kafka-topics.sh" --bootstrap-server "localhost:${KAFKA_INTERNAL_BROKER_PORT}" --list >/dev/null 2>&1
}

kafka_is_healthy() {
  local attempts="${KAFKA_HEALTH_RETRIES:-3}"
  local interval="${KAFKA_HEALTH_INTERVAL:-2}"
  local attempt

  for (( attempt = 1; attempt <= attempts; attempt++ )); do
    if kafka_is_ready; then
      return 0
    fi
    sleep "${interval}"
  done

  return 1
}

render_spark_config() {
  local spark_master_opts

  mkdir -p /var/lib/spark/work /var/lib/spark-events "${SPARK_HOME}/logs"

  spark_master_opts="-Dspark.master.rest.enabled=${SPARK_MASTER_REST_ENABLED} -Dspark.master.rest.port=${SPARK_MASTER_REST_PORT}"
  if [[ -n "${SPARK_MASTER_REST_HOST}" ]]; then
    spark_master_opts+=" -Dspark.master.rest.host=${SPARK_MASTER_REST_HOST}"
  fi

  cat > "${SPARK_HOME}/conf/spark-env.sh" <<EOF
export JAVA_HOME=${JAVA_HOME}
export SPARK_MASTER_HOST=${SPARK_MASTER_HOST}
export SPARK_MASTER_PORT=${SPARK_MASTER_PORT}
export SPARK_MASTER_WEBUI_PORT=${SPARK_MASTER_WEBUI_PORT}
export SPARK_WORKER_WEBUI_PORT=${SPARK_WORKER_WEBUI_PORT}
export SPARK_PUBLIC_DNS=${SPARK_PUBLIC_DNS}
export SPARK_LOG_DIR=${SPARK_HOME}/logs
export SPARK_WORKER_INSTANCES=${SPARK_WORKER_INSTANCES}
export SPARK_WORKER_CORES=${SPARK_WORKER_CORES}
export SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY}
export SPARK_WORKER_DIR=/var/lib/spark/work
export SPARK_WORKER_OPTS="${SPARK_WORKER_OPTS}"
export SPARK_HISTORY_OPTS="-Dspark.history.fs.logDirectory=/var/lib/spark-events -Dspark.history.ui.port=${SPARK_HISTORY_PORT} -Dspark.history.ui.host=${SPARK_HISTORY_UI_HOST}"
export SPARK_DAEMON_JAVA_OPTS="-Dspark.deploy.recoveryMode=NONE"
export SPARK_MASTER_OPTS="${spark_master_opts}"
export SPARK_LOCAL_IP=${SPARK_LOCAL_IP}
EOF

  cat > "${SPARK_HOME}/conf/spark-defaults.conf" <<EOF
spark.master                     spark://localhost:${SPARK_MASTER_PORT}
spark.eventLog.enabled           true
spark.eventLog.dir               file:///var/lib/spark-events
spark.history.fs.logDirectory    file:///var/lib/spark-events
spark.sql.warehouse.dir          /var/lib/spark-warehouse
EOF
}

start_spark() {
  render_spark_config
  log "Starting Spark master, history server, and workers"
  "${SPARK_HOME}/sbin/start-master.sh"
  "${SPARK_HOME}/sbin/start-history-server.sh"
  "${SPARK_HOME}/sbin/start-worker.sh" "spark://localhost:${SPARK_MASTER_PORT}"
}

render_osa_config() {
  local jdbc_url secured_db_password xml_db xml_user xml_password
  local osa_enable_ssl osa_ssl_fail_on_validations
  local ssl_certificate_password ssl_certificate_password_encrypted ssl_certificate_path
  local runtime_logs_dir="${OSA_RUNTIME_DIR}/logs"

  # OSA derives the schema name by splitting on the last "/" in the JDBC URL.
  # Keep the URL path bare so MySQL schema detection does not include query params.
  jdbc_url="jdbc:mysql://127.0.0.1:${MYSQL_TCP_PORT}/${MYSQL_DATABASE}"
  secured_db_password="$(generate_osa_secured_password "${MYSQL_PASSWORD}")"
  osa_enable_ssl="${OSA_ENABLE_SSL,,}"
  osa_ssl_fail_on_validations="${OSA_SSL_FAIL_ON_VALIDATIONS,,}"
  xml_db="$(xml_escape "${jdbc_url}")"
  xml_user="$(xml_escape "${MYSQL_USER}")"
  xml_password="$(xml_escape "${secured_db_password}")"

  mkdir -p "${OSA_RUNTIME_DIR}" "${OSA_BASE}/certificate" "${OSA_BASE}/logs"

  if [[ "${runtime_logs_dir}" != "${OSA_BASE}/logs" ]]; then
    if [[ -d "${runtime_logs_dir}" && ! -L "${runtime_logs_dir}" ]]; then
      cp -a "${runtime_logs_dir}/." "${OSA_BASE}/logs"/ 2>/dev/null || true
      rm -rf "${runtime_logs_dir}"
    else
      rm -f "${runtime_logs_dir}"
    fi
    ln -s "${OSA_BASE}/logs" "${runtime_logs_dir}"
  fi

  if [[ "${osa_enable_ssl}" == "true" ]]; then
    ssl_certificate_password="${OSA_SSL_CERT_PASSWORD:-${OSA_ADMIN_PASSWORD}}"
    ssl_certificate_password_encrypted="$(generate_osa_secured_password "${ssl_certificate_password}")"
    ssl_certificate_path="$(generate_osa_self_signed_certificate "${ssl_certificate_password}")"
  fi

  cat > "${OSA_RUNTIME_DIR}/osa-datasource.xml" <<EOF
<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_3.dtd">
<Configure id="Server" class="org.eclipse.jetty.server.Server">
    <New id="osads" class="org.eclipse.jetty.plus.jndi.Resource">
        <Arg>
            <Ref refid="wac"/>
        </Arg>
        <Arg>jdbc/OSADataSource</Arg>
        <Arg>
            <New class="com.mysql.cj.jdbc.MysqlConnectionPoolDataSource">
                <Set name="DataSourceName">jdbc</Set>
                <Set name="URL">${xml_db}</Set>
                <Set name="User">${xml_user}</Set>
                <Set name="Password">${xml_password}</Set>
            </New>
        </Arg>
    </New>
</Configure>
EOF

  if [[ "${osa_enable_ssl}" == "true" ]]; then
    cat > "${OSA_RUNTIME_DIR}/ssl.conf" <<EOF
NEED_SSL=true
OSA_SERVER_CRT_P12=${ssl_certificate_path}
OSA_SERVER_CRT_PWD=${ssl_certificate_password_encrypted}
OSA_SERVER_CRT_GENERATED_BY=app
OSA_SERVER_CRT_FAIL_ON_VALIDATIONS=${osa_ssl_fail_on_validations}
EOF
  else
    cat > "${OSA_RUNTIME_DIR}/ssl.conf" <<EOF
NEED_SSL=false
OSA_SERVER_CRT_P12=
OSA_SERVER_CRT_PWD=
OSA_SERVER_CRT_GENERATED_BY=app
OSA_SERVER_CRT_FAIL_ON_VALIDATIONS=true
EOF
  fi

  cat > "${OSA_RUNTIME_DIR}/standalone-env.sh" <<EOF
export OSA_VERSION=26.1.0.0.0

export OSA_API_SERVER_PORT=${OSA_API_SERVER_PORT}
export OSA_API_SERVER_SPORT=${OSA_API_SERVER_SPORT}
EOF
}

start_osa() {
  render_osa_config

  local osa_args=(
    "dbroot=${MYSQL_ROOT_USER}"
    "dbroot_password=${MYSQL_ROOT_PASSWORD}"
    "osaadmin_user=${OSA_ADMIN_USER}"
    "osaadmin_password=${OSA_ADMIN_PASSWORD}"
    "role=admin"
  )

  if [[ "${OSA_LOAD_SAMPLES}" != "true" ]]; then
    osa_args+=("--no-load-samples")
  fi

  log "Starting Oracle Stream Analytics"
  (
    cd "${OSA_BASE}/bin"

    hostname() {
      if [[ "${1:-}" == "-f" || "${1:-}" == "--fqdn" ]]; then
        printf '%s\n' "${OSA_PUBLIC_HOST}"
        return 0
      fi
      command hostname "$@"
    }

    jar() {
      command jar "$@"
      local status=$?
      if [[ ${status} -ne 0 ]]; then
        return "${status}"
      fi

      if [[ "${1:-}" == "xf" && "${2:-}" == "${OSA_RUNTIME_DIR}/api-server-19.1.3-100.jar" ]]; then
        sync_helidon_datasource_from_xml \
          "${OSA_RUNTIME_DIR}/osa-datasource.xml" \
          application-standalone.yaml \
          application-standalone-ssl.yaml
      fi
    }

    export -f hostname jar xml_unescape xml_set_value xml_datasource_class sed_escape_replacement sync_helidon_datasource_from_xml
    export OSAADMIN_PASSWORD="${OSA_ADMIN_PASSWORD}"
    ./start-osa.sh "${osa_args[@]}" "--extFolder=${OSA_RUNTIME_DIR}"
  )

  local timeout="${OSA_READY_TIMEOUT:-600}"
  local start_time=$SECONDS
  while (( SECONDS - start_time < timeout )); do
    if [[ -f "${OSA_BASE}/osa.pid" ]] && ps -p "$(cat "${OSA_BASE}/osa.pid")" >/dev/null 2>&1; then
      if [[ "${OSA_ENABLE_SSL,,}" == "true" ]]; then
        if curl -kfsS "https://127.0.0.1:${OSA_API_SERVER_SPORT}/osa/index.html" >/dev/null 2>&1; then
          return 0
        fi
      else
        if curl -fsS "http://127.0.0.1:${OSA_API_SERVER_PORT}/osa/index.html" >/dev/null 2>&1; then
          return 0
        fi
      fi
    fi
    sleep 3
  done

  log "OSA did not become ready within ${timeout} seconds"
  exit 1
}

osa_api_base_url() {
  if [[ "${OSA_ENABLE_SSL,,}" == "true" ]]; then
    printf 'https://127.0.0.1:%s/osa/services/v0.1' "${OSA_API_SERVER_SPORT}"
  else
    printf 'http://127.0.0.1:%s/osa/services/v0.1' "${OSA_API_SERVER_PORT}"
  fi
}

detect_adb_service_name() {
  local tnsnames_file="$1"

  awk '
    /^[[:space:]]*#/ { next }
    /^[[:space:]]*[A-Za-z0-9._-]+[[:space:]]*=/ {
      name=$0
      sub(/^[[:space:]]*/, "", name)
      sub(/[[:space:]]*=.*/, "", name)
      if (first == "") {
        first = name
      }
      lowered = tolower(name)
      if (lowered ~ /_high$/) {
        print name
        found = 1
        exit
      }
    }
    END {
      if (!found && first != "") {
        print first
      }
    }
  ' "${tnsnames_file}"
}

resolve_adb_service_name() {
  local tnsnames_file="$1"
  local requested_service_name="$2"

  awk -v requested="${requested_service_name}" '
    /^[[:space:]]*#/ { next }
    /^[[:space:]]*[A-Za-z0-9._-]+[[:space:]]*=/ {
      name=$0
      sub(/^[[:space:]]*/, "", name)
      sub(/[[:space:]]*=.*/, "", name)
      if (requested != "" && tolower(name) == tolower(requested)) {
        print name
        found = 1
        exit
      }
      if (first == "") {
        first = name
      }
      if (high == "" && tolower(name) ~ /_high$/) {
        high = name
      }
    }
    END {
      if (!found) {
        if (high != "") {
          print high
        } else if (first != "") {
          print first
        }
      }
    }
  ' "${tnsnames_file}"
}

package_osa_wallet() {
  local wallet_dir="$1"
  local wallet_zip="$2"
  local patched_dir

  patched_dir="$(mktemp -d)"
  cp -a "${wallet_dir}/." "${patched_dir}/"
  rm -f "${patched_dir}"/ojdbc.properties.backup*

  if [[ -f "${patched_dir}/tnsnames.ora" ]]; then
    sed -i -E 's/ssl_server_dn_match[[:space:]]*=[[:space:]]*yes/ssl_server_dn_match=no/Ig' "${patched_dir}/tnsnames.ora"
  fi

  if [[ -f "${patched_dir}/sqlnet.ora" ]]; then
    if grep -qi '^[[:space:]]*SSL_SERVER_DN_MATCH[[:space:]]*=' "${patched_dir}/sqlnet.ora"; then
      sed -i -E 's/^[[:space:]]*SSL_SERVER_DN_MATCH[[:space:]]*=.*/SSL_SERVER_DN_MATCH=no/I' "${patched_dir}/sqlnet.ora"
    else
      printf '\nSSL_SERVER_DN_MATCH=no\n' >> "${patched_dir}/sqlnet.ora"
    fi
  fi

  if [[ -f "${patched_dir}/ojdbc.properties" ]]; then
    sed -i -E '/^[[:space:]]*(user|password)[[:space:]]*=/Id' "${patched_dir}/ojdbc.properties"
    if grep -qi '^[[:space:]]*oracle.net.ssl_server_dn_match[[:space:]]*=' "${patched_dir}/ojdbc.properties"; then
      sed -i -E 's/^[[:space:]]*oracle\.net\.ssl_server_dn_match[[:space:]]*=.*/oracle.net.ssl_server_dn_match=false/I' "${patched_dir}/ojdbc.properties"
    else
      printf '\noracle.net.ssl_server_dn_match=false\n' >> "${patched_dir}/ojdbc.properties"
    fi
  else
    printf 'oracle.net.ssl_server_dn_match=false\n' > "${patched_dir}/ojdbc.properties"
  fi

  jar cfM "${wallet_zip}" -C "${patched_dir}" . >/dev/null
  rm -rf "${patched_dir}"
}

configure_osa_adb_connection() {
  local enabled="${OSA_AUTO_ADB_CONNECT:-true}"
  enabled="${enabled,,}"
  if [[ "${enabled}" != "true" && "${enabled}" != "1" && "${enabled}" != "yes" ]]; then
    log "Skipping OSA ADB connection bootstrap because OSA_AUTO_ADB_CONNECT=${OSA_AUTO_ADB_CONNECT:-}"
    return 0
  fi

  local wallet_dir="${OSA_ADB_WALLET_DIR:-/wallet}"
  if [[ ! -d "${wallet_dir}" ]]; then
    log "No ADB wallet found for OSA at ${wallet_dir}; skipping OSA ADB connection bootstrap"
    return 0
  fi

  local required_file
  for required_file in tnsnames.ora sqlnet.ora cwallet.sso; do
    if [[ ! -f "${wallet_dir}/${required_file}" ]]; then
      log "ADB wallet at ${wallet_dir} is missing ${required_file}; skipping OSA ADB connection bootstrap"
      return 0
    fi
  done

  local requested_service_name="${OSA_ADB_SERVICE_NAME:-}"
  local service_name
  service_name="$(resolve_adb_service_name "${wallet_dir}/tnsnames.ora" "${requested_service_name}")"
  if [[ -z "${service_name}" ]]; then
    log "Could not determine the ADB service name from ${wallet_dir}/tnsnames.ora; skipping OSA ADB connection bootstrap"
    return 0
  fi
  if [[ -n "${requested_service_name}" && "${service_name}" != "${requested_service_name}" ]]; then
    log "Using wallet service alias ${service_name} instead of metadata value ${requested_service_name}"
  fi

  local username="${OSA_ADB_USERNAME:-PG}"
  local password="${OSA_ADB_PASSWORD:-}"
  if [[ -z "${password}" ]]; then
    log "OSA_ADB_PASSWORD is empty; skipping OSA ADB connection bootstrap"
    return 0
  fi

  if ! command -v jq >/dev/null 2>&1; then
    log "jq is required for OSA ADB connection bootstrap but is not installed; skipping"
    return 0
  fi
  if ! command -v jar >/dev/null 2>&1; then
    log "jar is required to package the ADB wallet for OSA but is not installed; skipping"
    return 0
  fi

  local cookie_file wallet_zip api_base login_payload upload_response file_object_id file_name
  local connections_response existing_id parameters_json connection_payload save_response save_success
  local connection_name="${OSA_ADB_CONNECTION_NAME:-PeakGear_ADB}"
  local display_name="${OSA_ADB_CONNECTION_DISPLAY_NAME:-PeakGear ADB}"
  local description="${OSA_ADB_CONNECTION_DESCRIPTION:-Autonomous Database connection created automatically from the server wallet.}"

  cookie_file="$(mktemp)"
  api_base="$(osa_api_base_url)"
  login_payload="$(jq -cn --arg username "${OSA_ADMIN_USER}" --arg password "${OSA_ADMIN_PASSWORD}" \
    '{username:$username,password:$password}')"

  if ! curl -kfsS -c "${cookie_file}" -b "${cookie_file}" \
      -H "Content-Type: application/json" \
      -X POST "${api_base}/auth/token" \
      --data-binary @- <<<"${login_payload}" >/dev/null; then
    log "Could not authenticate to the local OSA API; skipping OSA ADB connection bootstrap"
    rm -f "${cookie_file}" "${wallet_zip}"
    return 0
  fi

  if ! connections_response="$(curl -kfsS -b "${cookie_file}" "${api_base}/connections/type/DatabaseConnection")"; then
    log "Could not read existing OSA database connections; skipping OSA ADB connection bootstrap"
    rm -f "${cookie_file}"
    return 0
  fi
  existing_id="$(jq -r \
    --arg name "${connection_name}" \
    --arg display_name "${display_name}" \
    '.data[]? | select((.wname? == $name) or (.name? == $name) or (.displayName? == $display_name) or (.metadata?.name? == $name) or (.metadata?.displayName? == $display_name)) | .id // empty' \
    <<<"${connections_response}" | head -n 1)"
  if [[ -n "${existing_id}" ]]; then
    log "Reusing existing OSA ADB connection ${connection_name}; preserving its wallet and target bindings"
    rm -f "${cookie_file}"
    return 0
  fi

  wallet_zip="$(mktemp --suffix=.zip)"
  if ! package_osa_wallet "${wallet_dir}" "${wallet_zip}" >/dev/null 2>&1; then
    log "Failed to package the ADB wallet for OSA; skipping OSA ADB connection bootstrap"
    rm -f "${cookie_file}" "${wallet_zip}"
    return 0
  fi

  if ! upload_response="$(curl -kfsS -b "${cookie_file}" \
      -F "file=@${wallet_zip};filename=wallet.zip" \
      "${api_base}/files")"; then
    log "Could not upload the ADB wallet to OSA; skipping OSA ADB connection bootstrap"
    rm -f "${cookie_file}" "${wallet_zip}"
    return 0
  fi

  if ! file_object_id="$(jq -er '.data.fileObjectId' <<<"${upload_response}")"; then
    log "OSA wallet upload response did not include a fileObjectId; skipping OSA ADB connection bootstrap"
    rm -f "${cookie_file}" "${wallet_zip}"
    return 0
  fi
  file_name="$(jq -r '.data.fileName // "wallet.zip"' <<<"${upload_response}")"

  parameters_json="$(jq -cn \
    --arg file_name "${file_name}" \
    --arg file_object_id "${file_object_id}" \
    --arg service_name "${service_name}" \
    --arg username "${username}" \
    --arg password "${password}" \
    '{
      serviceNameOrSIDDropdown: "wallet",
      walletArchive: {
        fileDisplayName: $file_name,
        fileObjectId: $file_object_id,
        type: "upload"
      },
      serviceNameOrSIDInput: $service_name,
      userName: $username,
      password: $password
    }')"

  connection_payload="$(jq -cn \
    --arg name "${connection_name}" \
    --arg display_name "${display_name}" \
    --arg description "${description}" \
    --argjson parameters "${parameters_json}" \
    '{
      createdAt: null,
      createdBy: null,
      updatedAt: null,
      updatedBy: null,
      name: $name,
      id: null,
      displayName: $display_name,
      description: $description,
      attachedTagNames: [],
      wname: $name,
      typeName: "DatabaseConnection",
      parameters: $parameters
    }')"

  if ! save_response="$(curl -kfsS -b "${cookie_file}" \
      -H "Content-Type: application/json" \
      -X POST "${api_base}/connections" \
      --data-binary @- <<<"${connection_payload}")"; then
    log "Could not create OSA ADB connection ${connection_name}; leaving OSA running"
    rm -f "${cookie_file}" "${wallet_zip}"
    return 0
  fi

  save_success="$(jq -r '.success // false' <<<"${save_response}")"
  if [[ "${save_success}" == "true" ]]; then
    log "Created OSA ADB connection ${connection_name} using service ${service_name}"
  else
    log "OSA ADB connection API returned an unsuccessful response for ${connection_name}; leaving OSA running"
  fi

  rm -f "${cookie_file}" "${wallet_zip}"
}

cleanup() {
  set +e

  if [[ -f "${OSA_BASE}/osa.pid" ]]; then
    log "Stopping Oracle Stream Analytics"
    (cd "${OSA_BASE}/bin" && ./stop-osa.sh) >/dev/null 2>&1 || true
  fi

  if pgrep -f 'org.apache.spark.deploy.history.HistoryServer' >/dev/null 2>&1; then
    log "Stopping Spark history server"
    "${SPARK_HOME}/sbin/stop-history-server.sh" >/dev/null 2>&1 || true
  fi
  if pgrep -f 'org.apache.spark.deploy.worker.Worker' >/dev/null 2>&1; then
    log "Stopping Spark workers"
    "${SPARK_HOME}/sbin/stop-worker.sh" >/dev/null 2>&1 || true
  fi
  if pgrep -f 'org.apache.spark.deploy.master.Master' >/dev/null 2>&1; then
    log "Stopping Spark master"
    "${SPARK_HOME}/sbin/stop-master.sh" >/dev/null 2>&1 || true
  fi

  if pgrep -f 'kafka.Kafka' >/dev/null 2>&1; then
    log "Stopping Kafka"
    "${KAFKA_HOME}/bin/kafka-server-stop.sh" >/dev/null 2>&1 || true
  fi

  if [[ -S "${MYSQL_SOCKET}" ]]; then
    log "Stopping MySQL"
    stop_mysql_if_running
  fi
}

monitor_services() {
  while true; do
    if ! pgrep -x mysqld >/dev/null 2>&1; then
      log "MySQL is no longer running"
      return 1
    fi
    if ! kafka_is_healthy; then
      log "Kafka is no longer responding on localhost:${KAFKA_INTERNAL_BROKER_PORT}"
      return 1
    fi
    if ! pgrep -f 'org.apache.spark.deploy.master.Master' >/dev/null 2>&1; then
      log "Spark master is no longer running"
      return 1
    fi
    if ! pgrep -f 'org.apache.spark.deploy.history.HistoryServer' >/dev/null 2>&1; then
      log "Spark history server is no longer running"
      return 1
    fi
    if [[ ! -f "${OSA_BASE}/osa.pid" ]] || ! ps -p "$(cat "${OSA_BASE}/osa.pid")" >/dev/null 2>&1; then
      log "OSA is no longer running"
      return 1
    fi
    sleep 5
  done
}

main() {
  export OSA_BASE="${OSA_BASE:-/u01/osa/osa-base}"
  export OSA_RUNTIME_DIR="${OSA_RUNTIME_DIR:-/tmp}"
  export APP_HOME="${APP_HOME:-${OSA_BASE}}"
  export DATA_HOME="${DATA_HOME:-${OSA_BASE}}"
  export JAVA_HOME="${JAVA_HOME:-/usr/lib/jvm/java-21-openjdk}"
  export SPARK_HOME="${SPARK_HOME:-/u01/spark}"
  export KAFKA_HOME="${KAFKA_HOME:-/u01/kafka}"
  export MYSQL_DATADIR="${MYSQL_DATADIR:-/var/lib/mysql}"
  export MYSQL_SOCKET="${MYSQL_SOCKET:-/var/lib/mysql/mysql.sock}"
  export MYSQL_PID_FILE="${MYSQL_PID_FILE:-/var/run/mysqld/mysqld.pid}"
  export MYSQL_TCP_PORT="${MYSQL_TCP_PORT:-3306}"
  export MYSQL_ROOT_USER="${MYSQL_ROOT_USER:-root}"
  export MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD:-oracle}"
  export MYSQL_DATABASE="${MYSQL_DATABASE:-osa}"
  export MYSQL_USER="${MYSQL_USER:-osa}"
  export MYSQL_PASSWORD="${MYSQL_PASSWORD:-welcome1}"
  export OSA_ADMIN_USER="${OSA_ADMIN_USER:-osaadmin}"
  export OSA_ADMIN_PASSWORD="${OSA_ADMIN_PASSWORD:-welcome1}"
  export OSA_PUBLIC_HOST="${OSA_PUBLIC_HOST:-localhost}"
  export OSA_ENABLE_SSL="${OSA_ENABLE_SSL:-true}"
  export OSA_SSL_CERT_PASSWORD="${OSA_SSL_CERT_PASSWORD:-${OSA_ADMIN_PASSWORD}}"
  export OSA_SSL_FAIL_ON_VALIDATIONS="${OSA_SSL_FAIL_ON_VALIDATIONS:-false}"
  export OSA_API_SERVER_PORT="${OSA_API_SERVER_PORT:-9080}"
  export OSA_API_SERVER_SPORT="${OSA_API_SERVER_SPORT:-9443}"
  export OSA_LOAD_SAMPLES="${OSA_LOAD_SAMPLES:-false}"
  export KAFKA_INTERNAL_BROKER_PORT="${KAFKA_INTERNAL_BROKER_PORT:-19092}"
  export KAFKA_BROKER_PORT="${KAFKA_BROKER_PORT:-9092}"
  export KAFKA_CONTROLLER_PORT="${KAFKA_CONTROLLER_PORT:-9093}"
  export KAFKA_ADVERTISED_LISTENERS="${KAFKA_ADVERTISED_LISTENERS:-PLAINTEXT://localhost:${KAFKA_BROKER_PORT}}"
  export SPARK_MASTER_HOST="${SPARK_MASTER_HOST:-localhost}"
  export SPARK_MASTER_PORT="${SPARK_MASTER_PORT:-7077}"
  export SPARK_MASTER_REST_ENABLED="${SPARK_MASTER_REST_ENABLED:-true}"
  export SPARK_MASTER_REST_PORT="${SPARK_MASTER_REST_PORT:-6066}"
  export SPARK_MASTER_REST_HOST="${SPARK_MASTER_REST_HOST:-}"
  export SPARK_MASTER_WEBUI_PORT="${SPARK_MASTER_WEBUI_PORT:-28080}"
  export SPARK_WORKER_WEBUI_PORT="${SPARK_WORKER_WEBUI_PORT:-28081}"
  export SPARK_PUBLIC_DNS="${SPARK_PUBLIC_DNS:-${OSA_PUBLIC_HOST}}"
  export SPARK_WORKER_INSTANCES="${SPARK_WORKER_INSTANCES:-2}"
  export SPARK_WORKER_CORES="${SPARK_WORKER_CORES:-8}"
  export SPARK_WORKER_MEMORY="${SPARK_WORKER_MEMORY:-2g}"
  export SPARK_WORKER_OPTS="${SPARK_WORKER_OPTS:--Dspark.executor.logs.rolling.strategy=size -Dspark.executor.logs.rolling.maxSize=52428800 -Dspark.executor.logs.rolling.maxRetainedFiles=5}"
  export SPARK_LOCAL_IP="${SPARK_LOCAL_IP:-0.0.0.0}"
  export SPARK_HISTORY_PORT="${SPARK_HISTORY_PORT:-28083}"
  export SPARK_HISTORY_UI_HOST="${SPARK_HISTORY_UI_HOST:-0.0.0.0}"
  export OSA_KAFKA_URL="${OSA_KAFKA_URL:-localhost:${KAFKA_INTERNAL_BROKER_PORT}}"
  export OSA_SPARK_URL="${OSA_SPARK_URL:-localhost}"
  export OSA_SPARK_STANDALONE_CONSOLE_PORT="${OSA_SPARK_STANDALONE_CONSOLE_PORT:-${SPARK_MASTER_WEBUI_PORT}}"
  export PATH="${KAFKA_HOME}/bin:${SPARK_HOME}/bin:${SPARK_HOME}/sbin:${OSA_BASE}/bin:${JAVA_HOME}/bin:${PATH}"

  configure_public_host

  require_env MYSQL_ROOT_PASSWORD
  require_env MYSQL_PASSWORD
  require_env OSA_ADMIN_PASSWORD

  trap cleanup EXIT SIGINT SIGTERM

  start_mysql
  start_kafka
  start_spark
  start_osa
  configure_osa_adb_connection

  log "Stack is ready"
  if [[ "${OSA_ENABLE_SSL,,}" == "true" ]]; then
    log "OSA UI: https://${OSA_PUBLIC_HOST}:${OSA_API_SERVER_SPORT}/osa/index.html"
  else
    log "OSA UI: http://${OSA_PUBLIC_HOST}:${OSA_API_SERVER_PORT}/osa/index.html"
  fi
  log "Spark UI: http://${OSA_PUBLIC_HOST}:${SPARK_MASTER_WEBUI_PORT}"
  if [[ "${SPARK_MASTER_REST_ENABLED,,}" == "true" ]]; then
    log "Spark REST submissions: http://${OSA_PUBLIC_HOST}:${SPARK_MASTER_REST_PORT}/v1/submissions/create"
  fi
  log "Kafka internal bootstrap: localhost:${KAFKA_INTERNAL_BROKER_PORT}"
  log "Kafka public bootstrap: ${KAFKA_ADVERTISED_LISTENERS#PLAINTEXT://}"
  log "MySQL database: ${MYSQL_DATABASE} on port ${MYSQL_TCP_PORT}"

  monitor_services
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  main "$@"
fi
