REM INSERTING into "SH"."PRODUCTS"
   SET DEFINE OFF;
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 138,
           'Soccer Cleats - Adult',
           'Soccer Cleats - Adult',
           'Soccer Clothing',
           2043,
           'Soccer Clothing',
           'Soccer / Football',
           204,
           'Soccer / Football',
           1,
           'U',
           'P',
           1,
           'STATUS',
           69.99,
           69.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 16,
           'Sonic Core Graphite Racquet',
           'Sonic Core Graphite Racquet',
           'Tennis Racquet',
           2011,
           'Tennis Racquet',
           'Tennis',
           201,
           'Tennis',
           1,
           'U',
           'P',
           1,
           'STATUS',
           299.99,
           299.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 20,
           'Match Used Autograph Racquet',
           'Match Used Autograph Racquet',
           'Tennis Racquet',
           2012,
           'Tennis Racquet',
           'Tennis',
           201,
           'Tennis',
           1,
           'U',
           'P',
           1,
           'STATUS',
           599.99,
           599.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 29,
           'Limited Edition Racquet',
           'Limited Edition Racquet',
           'Tennis Racquet',
           2012,
           'Tennis Racquet',
           'Tennis',
           201,
           'Tennis',
           1,
           'U',
           'P',
           1,
           'STATUS',
           499.99,
           499.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 139,
           'Tennis Balls Heavy Duty Felt 3',
           'Tennis Balls Heavy Duty Felt 3 can',
           'Tennis Balls',
           2014,
           'Tennis Balls',
           'Tennis',
           201,
           'Tennis',
           4,
           'U',
           'P',
           1,
           'STATUS',
           19.99,
           19.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 140,
           'Tennis Strings Natural Gut',
           'Tennis Strings Natural Gut',
           'Tennis Strings',
           2014,
           'Tennis Strings',
           'Tennis',
           201,
           'Tennis',
           1,
           'U',
           'P',
           1,
           'STATUS',
           29.99,
           29.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 141,
           'Tennis Strings Synthetic Gut',
           'Tennis Strings Synthetic Gut',
           'Tennis Strings',
           2014,
           'Tennis Strings',
           'Tennis',
           201,
           'Tennis',
           1,
           'U',
           'P',
           1,
           'STATUS',
           29.99,
           29.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 142,
           'Tennis Strings Hybrids',
           'Tennis Strings Hybrids',
           'Tennis Strings',
           2014,
           'Tennis Strings',
           'Tennis',
           201,
           'Tennis',
           1,
           'U',
           'P',
           1,
           'STATUS',
           19.99,
           19.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 143,
           'Tennis Strings Polyester',
           'Tennis Strings Polyester',
           'Tennis Strings',
           2014,
           'Tennis Strings',
           'Tennis',
           201,
           'Tennis',
           1,
           'U',
           'P',
           1,
           'STATUS',
           19.99,
           19.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 144,
           'Tennis Grip Overgrip Tacky',
           'Tennis Grip Overgrip Tacky',
           'Tennis Racquet Grip',
           2014,
           'Tennis Racquet Grip',
           'Tennis',
           201,
           'Tennis',
           1,
           'U',
           'P',
           1,
           'STATUS',
           7.99,
           7.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 145,
           'Practice Tennis Balls',
           'Practice Tennis Balls',
           'Tennis Balls',
           2014,
           'Tennis Balls',
           'Tennis',
           201,
           'Tennis',
           1,
           'U',
           'P',
           1,
           'STATUS',
           12.99,
           12.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 146,
           'Regular Duty Tennis Balls',
           'Regular Duty Tennis Balls',
           'Tennis Balls',
           2014,
           'Tennis Balls',
           'Tennis',
           201,
           'Tennis',
           1,
           'U',
           'P',
           1,
           'STATUS',
           11.99,
           11.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 147,
           'Cushioned Grip',
           'Cushioned Grip',
           'Tennis Racquet Grip',
           2013,
           'Tennis Racquet Grip',
           'Tennis',
           201,
           'Tennis',
           1,
           'U',
           'P',
           1,
           'STATUS',
           7.99,
           7.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 148,
           'Tennis Balls 12 Pack',
           'Tennis Balls 12 Pack',
           'Tennis Balls',
           2013,
           'Tennis Balls',
           'Tennis',
           201,
           'Tennis',
           1,
           'U',
           'P',
           1,
           'STATUS',
           20.99,
           20.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 24,
           'Endurance Coolcore 1/2 Zip Pullover',
           'Endurance Coolcore 1/2 Zip Pullover',
           'Baseball Clothing',
           2034,
           'Baseball Clothing',
           'Baseball',
           203,
           'Baseball',
           1,
           'U',
           'P',
           1,
           'STATUS',
           45.99,
           45.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 25,
           '5 Point Batting Tee',
           '5 Point Batting Tee',
           'Batting Tees',
           2033,
           'Batting Tees',
           'Baseball',
           203,
           'Baseball',
           1,
           'U',
           'P',
           1,
           'STATUS',
           112.99,
           112.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 26,
           'Pro Style Batting Tee',
           'Pro Style Batting Tee',
           'Batting Tees',
           2033,
           'Batting Tees',
           'Baseball',
           203,
           'Baseball',
           1,
           'U',
           'P',
           1,
           'STATUS',
           149.99,
           149.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 27,
           'Bucket of 24 Synthetic Baseballs',
           'Bucket of 24 Synthetic Baseballs',
           'Baseballs',
           2031,
           'Baseballs',
           'Baseball',
           203,
           'Baseball',
           1,
           'U',
           'P',
           1,
           'STATUS',
           44.99,
           44.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 32,
           'Bucket of 24 Leather Baseballs',
           'Bucket of 24 Leather Baseballs',
           'Baseballs',
           2031,
           'Baseballs',
           'Baseball',
           203,
           'Baseball',
           1,
           'U',
           'P',
           1,
           'STATUS',
           67.99,
           67.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 33,
           'Baseball Is Life Cap',
           'Baseball Is Life Cap',
           'Baseball Clothing',
           2034,
           'Baseball Clothing',
           'Baseball',
           203,
           'Baseball',
           1,
           'U',
           'P',
           1,
           'STATUS',
           44.99,
           44.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 34,
           '11.5" Youth Triple Stripe Series Glove',
           '11.5" Youth Triple Stripe Series Glove',
           'Gloves and Mitts',
           2032,
           'Gloves and Mitts',
           'Baseball',
           203,
           'Baseball',
           1,
           'U',
           'P',
           1,
           'STATUS',
           39.99,
           39.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 35,
           'Catchers Mitt',
           'Catchers Mitt',
           'Gloves and Mitts',
           2032,
           'Gloves and Mitts',
           'Baseball',
           203,
           'Baseball',
           1,
           'U',
           'P',
           1,
           'STATUS',
           49.99,
           49.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 36,
           '12" Premium Series Glove',
           '12" Premium Series Glove',
           'Gloves and Mitts',
           2032,
           'Gloves and Mitts',
           'Baseball',
           203,
           'Baseball',
           1,
           'U',
           'P',
           1,
           'STATUS',
           44.99,
           44.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 37,
           '12.75" Premium Series Glove',
           '12.75" Premium Series Glove',
           'Gloves and Mitts',
           2032,
           'Gloves and Mitts',
           'Baseball',
           203,
           'Baseball',
           1,
           'U',
           'P',
           1,
           'STATUS',
           54.99,
           54.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 38,
           '11" Youth Field Master Glove',
           '11" Youth Field Master Glove',
           'Gloves and Mitts',
           2032,
           'Gloves and Mitts',
           'Baseball',
           203,
           'Baseball',
           1,
           'U',
           'P',
           1,
           'STATUS',
           29.99,
           29.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 39,
           '13" Field Master Series Glove',
           '13" Field Master Series Glove',
           'Gloves and Mitts',
           2032,
           'Gloves and Mitts',
           'Baseball',
           203,
           'Baseball',
           1,
           'U',
           'P',
           1,
           'STATUS',
           34.99,
           34.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 14,
           'Pitching Machine and Batting Cage Combo',
           'Pitching Machine and Batting Cage Combo',
           'Training Aids and Equipment',
           2035,
           'Training Aids and Equipment',
           'Baseball',
           203,
           'Baseball',
           1,
           'U',
           'P',
           1,
           'STATUS',
           999.99,
           999.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 21,
           'Speed Trainer Bats and Training Program',
           'Speed Trainer Bats and Training Program',
           'Training Aids and Equipment',
           2035,
           'Training Aids and Equipment',
           'Baseball',
           203,
           'Baseball',
           1,
           'U',
           'P',
           1,
           'STATUS',
           899.99,
           899.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 22,
           'MLB Official Game Baseball w/ Display Case',
           'MLB Official Game Baseball w/ Display Case',
           'Baseballs',
           2031,
           'Baseballs',
           'Baseball',
           203,
           'Baseball',
           1,
           'U',
           'P',
           1,
           'STATUS',
           24.99,
           24.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 46,
           '2 Competition Grade NFHS Baseballs',
           '2 Competition Grade NFHS Baseballs',
           'Baseballs',
           2031,
           'Baseballs',
           'Baseball',
           203,
           'Baseball',
           1,
           'U',
           'P',
           1,
           'STATUS',
           22.99,
           22.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 47,
           '6 Gallon Empty Ball Bucket',
           '6 Gallon Empty Ball Bucket',
           'Baseballs',
           2031,
           'Baseballs',
           'Baseball',
           203,
           'Baseball',
           1,
           'U',
           'P',
           1,
           'STATUS',
           28.99,
           28.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 127,
           'Genuine Series MIX Wood Bat',
           'Genuine Series MIX Wood Bat',
           'Bats',
           2036,
           'Bats',
           'Baseball',
           203,
           'Baseball',
           1,
           'U',
           'P',
           1,
           'STATUS',
           36.99,
           36.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 128,
           'Slugger Youth Series Maple Bat',
           'Slugger Youth Series Maple Bat',
           'Bats',
           2036,
           'Bats',
           'Baseball',
           203,
           'Baseball',
           1,
           'U',
           'P',
           1,
           'STATUS',
           27.99,
           27.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 129,
           'Pro Maple Bat',
           'Pro Maple Bat',
           'Bats',
           2036,
           'Bats',
           'Baseball',
           203,
           'Baseball',
           1,
           'U',
           'P',
           1,
           'STATUS',
           192.99,
           192.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 130,
           'Pro Maple Youth Bat',
           'Pro Maple Youth Bat',
           'Bats',
           2036,
           'Bats',
           'Baseball',
           203,
           'Baseball',
           1,
           'U',
           'P',
           1,
           'STATUS',
           89.99,
           89.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 19,
           'Cricket Bat Bag',
           'Cricket bat bag',
           'Cricket Bat',
           2051,
           'Cricket Bat',
           'Cricket',
           205,
           'Cricket',
           1,
           'U',
           'P',
           1,
           'STATUS',
           55.99,
           55.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 23,
           'Plastic Cricket Bat',
           'Plastic - Beach Cricket Bat',
           'Cricket Bat',
           2051,
           'Cricket',
           'Cricket',
           205,
           'Cricket',
           1,
           'U',
           'P',
           1,
           'STATUS',
           21.99,
           21.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 28,
           'English Willow Cricket Bat',
           'English Willow Cricket Bat',
           'Cricket Bat',
           2051,
           'Cricket Bat',
           'Cricket',
           205,
           'Cricket',
           1,
           'U',
           'P',
           1,
           'STATUS',
           199.99,
           199.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 30,
           'Linseed Oil',
           'Cricket Bat - Linseed Oil',
           'Cricket Bat',
           2051,
           'Cricket Bat',
           'Cricket',
           205,
           'Cricket',
           1,
           'U',
           'P',
           1,
           'STATUS',
           9.99,
           9.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 31,
           'Fiber Tape',
           'Cricket Bat - Fiber Tape',
           'Cricket Bat',
           2051,
           'Cricket Bat',
           'Cricket',
           205,
           'Cricket',
           1,
           'U',
           'P',
           1,
           'STATUS',
           8.99,
           8.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 40,
           'Team shirt',
           'West Indies Team',
           'Cricket Fan Gear',
           2054,
           'Cricket Fan Gear',
           'Cricket',
           205,
           'Cricket',
           1,
           'U',
           'P',
           1,
           'STATUS',
           44.99,
           44.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 41,
           'Team shirt',
           'South African Team',
           'Cricket Fan Gear',
           2054,
           'Cricket Fan Gear',
           'Cricket',
           205,
           'Cricket',
           1,
           'U',
           'P',
           1,
           'STATUS',
           44.99,
           44.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 42,
           'Team shirt',
           'New Zealand Cricket Team',
           'Cricket Fan Gear',
           2054,
           'Cricket Fan Gear',
           'Cricket',
           205,
           'Cricket',
           1,
           'U',
           'P',
           1,
           'STATUS',
           44.99,
           44.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 43,
           'Team shirt',
           'Australian Cricket Team',
           'Cricket Fan Gear',
           2054,
           'Cricket Fan Gear',
           'Cricket',
           205,
           'Cricket',
           1,
           'U',
           'P',
           1,
           'STATUS',
           44.99,
           44.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 44,
           'Team shirt',
           'Indian Cricket Team',
           'Cricket Fan Gear',
           2054,
           'Cricket Fan Gear',
           'Cricket',
           205,
           'Cricket',
           1,
           'U',
           'P',
           1,
           'STATUS',
           44.99,
           44.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 45,
           'Team shirt',
           'English Cricket Team',
           'Cricket Fan Gear',
           2054,
           'Cricket Fan Gear',
           'Cricket',
           205,
           'Cricket',
           1,
           'U',
           'P',
           1,
           'STATUS',
           44.99,
           44.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 48,
           'Indoor Cricket Ball',
           'Indoor Cricket Ball',
           'Cricket',
           2055,
           'Cricket',
           'Cricket',
           205,
           'Cricket',
           1,
           'U',
           'P',
           1,
           'STATUS',
           11.99,
           11.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 113,
           'Cricket Ball',
           'Cricket Ball - Leather',
           'Cricket',
           2055,
           'Cricket',
           'Cricket',
           205,
           'Cricket',
           1,
           'U',
           'P',
           1,
           'STATUS',
           22.99,
           22.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 114,
           'Cricket Ball - Training Ball',
           'Cricket Ball - Training',
           'Cricket',
           2055,
           'Cricket',
           'Cricket',
           205,
           'Cricket',
           1,
           'U',
           'P',
           1,
           'STATUS',
           18.99,
           18.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 115,
           'Plastic - Beach Cricket Ball',
           'Plastic - Beach Cricket Ball',
           'Cricket',
           2055,
           'Cricket',
           'Cricket',
           205,
           'Cricket',
           1,
           'U',
           'P',
           1,
           'STATUS',
           8.99,
           8.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 116,
           'Catchers Helmet',
           'Catchers Helmet',
           'Cricket',
           2055,
           'Cricket',
           'Cricket',
           205,
           'Cricket',
           1,
           'U',
           'P',
           1,
           'STATUS',
           11.99,
           11.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 117,
           'Plastic - Beach Cricket Wickets',
           'Plastic - Beach Cricket Wickets',
           'Cricket',
           2055,
           'Cricket',
           'Cricket',
           205,
           'Cricket',
           1,
           'U',
           'P',
           1,
           'STATUS',
           8.99,
           8.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 118,
           'Cricket Bails',
           'Cricket Bails',
           'Cricket',
           2055,
           'Cricket',
           'Cricket',
           205,
           'Cricket',
           1,
           'U',
           'P',
           1,
           'STATUS',
           7.99,
           7.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 119,
           'Cricket Bails - Junior',
           'Cricket Bails - Junior',
           'Cricket',
           2055,
           'Cricket',
           'Cricket',
           205,
           'Cricket',
           1,
           'U',
           'P',
           1,
           'STATUS',
           6.99,
           6.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 120,
           'Cricket Peak Cap',
           'Cricket Peak Cap',
           'Cricket Clothing',
           2056,
           'Cricket Clothing',
           'Cricket',
           205,
           'Cricket',
           1,
           'U',
           'P',
           1,
           'STATUS',
           6.99,
           6.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 121,
           'Cricket - Athletic Guard Cup',
           'Cricket - Athletic Guard Cup',
           'Cricket Clothing',
           2056,
           'Cricket Clothing',
           'Cricket',
           205,
           'Cricket',
           1,
           'U',
           'P',
           1,
           'STATUS',
           10.99,
           10.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 122,
           'Wide Brim Hat',
           'Cricket Wide Brim Hat',
           'Cricket Clothing',
           2056,
           'Cricket Clothing',
           'Cricket',
           205,
           'Cricket',
           1,
           'U',
           'P',
           1,
           'STATUS',
           18.99,
           18.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 123,
           'Helmet',
           'Cricket Helmet',
           'Cricket Clothing',
           2056,
           'Cricket Clothing',
           'Cricket',
           205,
           'Cricket',
           1,
           'U',
           'P',
           1,
           'STATUS',
           49.99,
           49.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 124,
           'Wicket Keeper Gloves',
           'Wicket Keeper Gloves',
           'Cricket Clothing',
           2056,
           'Cricket Clothing',
           'Cricket',
           205,
           'Cricket',
           1,
           'U',
           'P',
           1,
           'STATUS',
           18.99,
           18.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 125,
           'Bucket Hat',
           'Cricket Bucket Hat',
           'Cricket Clothing',
           2053,
           'Cricket Clothing',
           'Cricket',
           205,
           'Cricket',
           1,
           'U',
           'P',
           1,
           'STATUS',
           15.99,
           15.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 126,
           'Spiked Shoes',
           'Spiked Cricket Shoes',
           'Cricket Clothing',
           2053,
           'Cricket Clothing',
           'Cricket',
           205,
           'Cricket',
           1,
           'U',
           'P',
           1,
           'STATUS',
           28.99,
           28.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 15,
           'Right-Handed Graphite Shaft Iron Set',
           'Right-Handed Graphite Shaft Iron Set',
           'Irons and Iron Sets',
           2021,
           'Irons and Iron Sets',
           'Golf',
           202,
           'Golf',
           1,
           'U',
           'P',
           1,
           'STATUS',
           999.99,
           999.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 18,
           'Lithium Electric Golf Caddy',
           'Lithium Electric Golf Caddy',
           'Golf Bags and Carts',
           2022,
           'Golf Bags and Carts',
           'Golf',
           202,
           'Golf',
           1,
           'U',
           'P',
           1,
           'STATUS',
           1299.99,
           1299.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 13,
           'Soccer Goal - Portable',
           'Soccer Goal - Portable',
           'Soccer / Football',
           2044,
           'Soccer / Football',
           'Soccer / Football',
           204,
           'Soccer / Football',
           1,
           'U',
           'P',
           1,
           'STATUS',
           899.99,
           899.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 17,
           'Soccer Goal - Official',
           'Soccer Goal - Official',
           'Soccer / Football',
           2041,
           'Soccer / Football',
           'Soccer / Football',
           204,
           'Soccer / Football',
           1,
           'U',
           'P',
           1,
           'STATUS',
           1099.99,
           1099.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 131,
           'Soccer Ball - Size 4',
           'Soccer Ball - Size 4 Youth',
           'Soccer Equipment',
           2042,
           'Soccer Equipment',
           'Soccer / Football',
           204,
           'Soccer / Football',
           1,
           'U',
           'P',
           1,
           'STATUS',
           18.99,
           18.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 132,
           'Soccer Ball - Size 5',
           'Soccer Ball - Size 5',
           'Soccer Equipment',
           2042,
           'Soccer Equipment',
           'Soccer / Football',
           204,
           'Soccer / Football',
           1,
           'U',
           'P',
           1,
           'STATUS',
           24.99,
           24.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 133,
           'Goal Keeper Gloves',
           'Goal Keeper Gloves',
           'Soccer Equipment',
           2042,
           'Soccer Equipment',
           'Soccer / Football',
           204,
           'Soccer / Football',
           1,
           'U',
           'P',
           1,
           'STATUS',
           30.99,
           30.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 134,
           'Shin Guards',
           'Shin Guards',
           'Soccer Equipment',
           2042,
           'Soccer Equipment',
           'Soccer / Football',
           204,
           'Soccer / Football',
           1,
           'U',
           'P',
           1,
           'STATUS',
           20.99,
           20.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 135,
           'Gear Bag',
           'Gear Bag',
           'Soccer Equipment',
           2042,
           'Soccer Equipment',
           'Soccer / Football',
           204,
           'Soccer / Football',
           1,
           'U',
           'P',
           1,
           'STATUS',
           49.99,
           49.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 136,
           'Soccer Jersey',
           'Soccer Jersey',
           'Soccer Clothing',
           2043,
           'Soccer Clothing',
           'Soccer / Football',
           204,
           'Soccer / Football',
           1,
           'U',
           'P',
           1,
           'STATUS',
           32.99,
           32.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 137,
           'Soccer Cleats - Junior',
           'Soccer Cleats - Junior',
           'Soccer Clothing',
           2043,
           'Soccer Clothing',
           'Soccer / Football',
           204,
           'Soccer / Football',
           1,
           'U',
           'P',
           1,
           'STATUS',
           52.99,
           52.99,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );
insert into "SH"."PRODUCTS" (
   prod_id,
   prod_name,
   prod_desc,
   prod_subcategory,
   prod_subcategory_id,
   prod_subcategory_desc,
   prod_category,
   prod_category_id,
   prod_category_desc,
   prod_weight_class,
   prod_unit_of_measure,
   prod_pack_size,
   supplier_id,
   prod_status,
   prod_list_price,
   prod_min_price,
   prod_total,
   prod_total_id,
   prod_src_id,
   prod_eff_from,
   prod_eff_to,
   prod_valid
) values ( 1902,
           'Soccer Cup - Blue and white stripes',
           'Soccer Cup - Blue and white stripes',
           'Soccer Memorabilia',
           2043,
           'Soccer Memorabilia',
           'Soccer / Football',
           204,
           'Soccer / Football',
           1,
           'U',
           'P',
           1,
           'STATUS',
           19.02,
           19.02,
           'TOTAL',
           1,
           null,
           to_date('01/01/19','DD/MM/RR'),
           null,
           'A' );