/*
 * 10_returns_graph.sql
 * Dedicated returns entity property graph for PeakGear retail returns operations demos.
 */

SET SERVEROUTPUT ON
PROMPT Creating returns graph schema...

BEGIN
    EXECUTE IMMEDIATE 'DROP PROPERTY GRAPH returns_network';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-942, -1403, -4043) THEN
            DBMS_OUTPUT.PUT_LINE('Skipping returns_network drop: ' || SQLERRM);
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP PROPERTY GRAPH returns_relationship_graph';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-942, -1403, -4043) THEN
            DBMS_OUTPUT.PUT_LINE('Skipping returns_relationship_graph drop: ' || SQLERRM);
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE returns_case_entities CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE returns_relationships CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE returns_cases CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE returns_entities CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE returns_entities (
    entity_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    entity_key         VARCHAR2(64) NOT NULL UNIQUE,
    display_name       VARCHAR2(160) NOT NULL,
    entity_type        VARCHAR2(30) NOT NULL
                       CHECK (entity_type IN (
                         'customer_account','order','receipt','product','store',
                         'refund_method','promotion','contact','outlet_channel','case_anchor'
                       )),
    review_score         NUMBER(5,2) DEFAULT 0 NOT NULL,
    review_level         VARCHAR2(16) DEFAULT 'medium' NOT NULL
                       CHECK (review_level IN ('critical','high','medium','low')),
    region             VARCHAR2(80),
    city               VARCHAR2(80),
    channel            VARCHAR2(32) DEFAULT 'unknown' NOT NULL
                       CHECK (channel IN (
                         'mobile','web','store','pos','contact_center',
                         'returns','outlet','order_service','unknown'
                       )),
    total_amount       NUMBER(14,2) DEFAULT 0 NOT NULL,
    event_count        NUMBER(8) DEFAULT 0 NOT NULL,
    first_seen         TIMESTAMP DEFAULT SYSTIMESTAMP,
    last_seen          TIMESTAMP DEFAULT SYSTIMESTAMP,
    is_confirmed_returns NUMBER(1) DEFAULT 0 NOT NULL
                       CHECK (is_confirmed_returns IN (0, 1))
);

CREATE INDEX idx_returns_entities_type ON returns_entities(entity_type);
CREATE INDEX idx_returns_entities_review ON returns_entities(review_score DESC);
CREATE INDEX idx_returns_entities_channel ON returns_entities(channel);

CREATE TABLE returns_relationships (
    relationship_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    from_entity       NUMBER NOT NULL REFERENCES returns_entities(entity_id),
    to_entity         NUMBER NOT NULL REFERENCES returns_entities(entity_id),
    relationship_type VARCHAR2(40) NOT NULL
                      CHECK (relationship_type IN (
                        'same_order','same_receipt','settled_to_credit','refund_method',
                        'promotion_used','order_verified_by','opened_with','same_contact',
                        'same_product','resale_channel','outlet_velocity','store_origin'
                      )),
    strength          NUMBER(4,3) DEFAULT 0.5 NOT NULL,
    event_count       NUMBER(8) DEFAULT 1 NOT NULL,
    total_amount      NUMBER(14,2) DEFAULT 0 NOT NULL,
    first_seen        TIMESTAMP DEFAULT SYSTIMESTAMP,
    last_seen         TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT uq_returns_relationship UNIQUE (from_entity, to_entity, relationship_type)
);

CREATE INDEX idx_returns_rel_from ON returns_relationships(from_entity);
CREATE INDEX idx_returns_rel_to ON returns_relationships(to_entity);
CREATE INDEX idx_returns_rel_type ON returns_relationships(relationship_type);

CREATE TABLE returns_cases (
    case_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    case_ref     VARCHAR2(64) NOT NULL UNIQUE,
    case_type    VARCHAR2(60) NOT NULL,
    status       VARCHAR2(30) DEFAULT 'reviewing' NOT NULL
                 CHECK (status IN ('reviewing','escalated','monitoring','resolved','closed')),
    review_score   NUMBER(5,2) DEFAULT 0 NOT NULL,
    loss_amount  NUMBER(14,2) DEFAULT 0 NOT NULL,
    event_count  NUMBER(8) DEFAULT 0 NOT NULL,
    opened_at    TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at   TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE returns_case_entities (
    case_entity_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    case_id        NUMBER NOT NULL REFERENCES returns_cases(case_id),
    entity_id      NUMBER NOT NULL REFERENCES returns_entities(entity_id),
    role           VARCHAR2(40) NOT NULL
                   CHECK (role IN ('seed','related_account','shared_order','refund_method','store','outlet','promotion','watchlist')),
    evidence_score NUMBER(5,2) DEFAULT 0 NOT NULL,
    CONSTRAINT uq_returns_case_entity UNIQUE (case_id, entity_id, role)
);

CREATE INDEX idx_returns_case_entities_case ON returns_case_entities(case_id);
CREATE INDEX idx_returns_case_entities_entity ON returns_case_entities(entity_id);

CREATE PROPERTY GRAPH returns_relationship_graph
    VERTEX TABLES (
        returns_entities KEY (entity_id)
            LABEL entity
            PROPERTIES (
                entity_id,
                entity_key,
                display_name,
                entity_type,
                review_score,
                review_level,
                region,
                city,
                channel,
                total_amount,
                event_count,
                is_confirmed_returns
            ),
        returns_cases KEY (case_id)
            LABEL returns_case
            PROPERTIES (
                case_id,
                case_ref,
                case_type,
                status,
                review_score,
                loss_amount,
                event_count
            )
    )
    EDGE TABLES (
        returns_relationships
            KEY (relationship_id)
            SOURCE KEY (from_entity) REFERENCES returns_entities (entity_id)
            DESTINATION KEY (to_entity) REFERENCES returns_entities (entity_id)
            LABEL related_to
            PROPERTIES (
                relationship_type,
                strength,
                event_count,
                total_amount
            ),
        returns_case_entities
            KEY (case_entity_id)
            SOURCE KEY (case_id) REFERENCES returns_cases (case_id)
            DESTINATION KEY (entity_id) REFERENCES returns_entities (entity_id)
            LABEL contains_entity
            PROPERTIES (
                role,
                evidence_score
            )
    );

COMMIT;

SELECT 'Returns property graph schema ready' AS status FROM dual;
