const crypto = require('node:crypto');
const NON_TERMINAL_STATUSES = new Set(['admitted', 'applying']);
const readNonTerminalGeneration = () => require('./datasetGenerationStore').readNonTerminalGeneration();
let activeTransition = null; let activeReaders = 0; const waiters = new Set();
function isDatasetFenceExemptRequest(method, path) { const value = String(path || '/').split('?')[0]; return String(method || 'GET').toUpperCase() === 'OPTIONS' || value === '/health' || value === '/demo-session' || /^\/import\/status\/[^/]+\/?$/.test(value); }
function getDatasetServingTransition() { return activeTransition && { ...activeTransition }; }
function beginDatasetServingTransition(metadata = {}) { if (activeTransition) { const error = new Error('A destructive dataset generation transition is already active.'); error.code = 'DATASET_GENERATION_TRANSITION_ACTIVE'; error.statusCode = 409; throw error; } activeTransition = { transitionToken: crypto.randomUUID(), generationId: metadata.generationId || null, jobId: metadata.jobId || null, status: 'admitted' }; return activeTransition.transitionToken; }
function associateDatasetServingTransition(token, metadata = {}) { if (!activeTransition || activeTransition.transitionToken !== token) throw new Error('Dataset serving transition ownership was lost.'); Object.assign(activeTransition, metadata); return getDatasetServingTransition(); }
function endDatasetServingTransition({ transitionToken } = {}) { if (!activeTransition || activeTransition.transitionToken !== transitionToken) return false; activeTransition = null; return true; }
function waitForDatasetReadersToDrain({ transitionToken } = {}) { if (!activeTransition || activeTransition.transitionToken !== transitionToken) return Promise.reject(new Error('Dataset serving transition ownership was lost before reader drain.')); return activeReaders ? new Promise((resolve) => waiters.add(resolve)) : Promise.resolve(); }
function planDatasetServingRequest({ method, path, generation, localTransition, lookupFailed = false } = {}) { if (isDatasetFenceExemptRequest(method, path)) return { allow: true, exempt: true }; const pending = localTransition || generation; if (pending && NON_TERMINAL_STATUSES.has(String(pending.status || '').toLowerCase())) return { allow: false, statusCode: 503, code: 'DATASET_GENERATION_TRANSITION', retryAfterSeconds: 2, generation: pending }; return lookupFailed ? { allow: false, statusCode: 503, code: 'DATASET_GENERATION_FENCE_UNAVAILABLE', retryAfterSeconds: 2 } : { allow: true, exempt: false }; }
function fence(res, decision) { res.setHeader('Retry-After', String(decision.retryAfterSeconds || 2)); return res.status(decision.statusCode).json({ ok: false, error: 'Dataset generation transition is in progress.', code: decision.code, retryable: true, generation: decision.generation || null }); }
function createDatasetServingFence({ lookupGeneration = readNonTerminalGeneration } = {}) { return async (req, res, next) => { let decision = planDatasetServingRequest({ method: req.method, path: req.path, localTransition: getDatasetServingTransition() }); if (decision.exempt) return next(); if (!decision.allow) return fence(res, decision); let generation; try { generation = await lookupGeneration(); } catch (_) { return fence(res, planDatasetServingRequest({ method: req.method, path: req.path, lookupFailed: true })); } decision = planDatasetServingRequest({ method: req.method, path: req.path, generation, localTransition: getDatasetServingTransition() }); if (!decision.allow) return fence(res, decision); activeReaders += 1; let released = false; const release = () => { if (released) return; released = true; activeReaders -= 1; if (!activeReaders) { for (const resolve of waiters) resolve(); waiters.clear(); } }; res.once('finish', release); res.once('close', release); return next(); }; }
module.exports = { isDatasetFenceExemptRequest, planDatasetServingRequest, getDatasetServingTransition, beginDatasetServingTransition, associateDatasetServingTransition, endDatasetServingTransition, waitForDatasetReadersToDrain, createDatasetServingFence };
