const crypto = require('crypto');
const db = require('../config/database');
const LEASE_SECONDS = Math.max(60, Number(process.env.DATASET_OPERATION_LEASE_SECONDS || 1800));
const SELECT_LOCK = `SELECT lease_token,owner_job_id,operation_kind,status,message,progress,lease_expires_at,CASE WHEN lease_token IS NOT NULL AND lease_expires_at <= SYSTIMESTAMP THEN 1 ELSE 0 END stale FROM app_dataset_operation_lock WHERE lock_id=1`;
function normalize(row) { if (!row?.LEASE_TOKEN) return null; return { leaseToken: row.LEASE_TOKEN, jobId: row.OWNER_JOB_ID || null, kind: row.OPERATION_KIND || null, status: row.STATUS || null, message: row.MESSAGE || null, progress: Number(row.PROGRESS || 0), stale: Number(row.STALE || 0) === 1 }; }
async function getActiveOperation() { let connection; try { connection = await db.getConnection(); const result = await connection.execute(SELECT_LOCK); const operation = normalize(result.rows[0]); return operation?.stale ? null : operation; } finally { if (connection) try { await connection.close(); } catch (_) {} } }
async function beginOperation(metadata = {}) { let connection; try { connection = await db.getConnection(); let result; try { result = await connection.execute(`${SELECT_LOCK} FOR UPDATE NOWAIT`, {}, { autoCommit: false }); } catch (error) { if (/ORA-00054/.test(String(error.message || ''))) return null; throw error; } const active = normalize(result.rows[0]); if (active && !active.stale) return null; const operation = { leaseToken: crypto.randomUUID(), jobId: metadata.jobId || null, kind: metadata.kind || 'dataset_operation', status: metadata.status || 'running', message: metadata.message || 'Dataset operation in progress.', progress: Number(metadata.progress || 0), leaseSeconds: LEASE_SECONDS }; await connection.execute(`UPDATE app_dataset_operation_lock SET lease_token=:leaseToken,owner_job_id=:jobId,operation_kind=:kind,status=:status,message=:message,progress=:progress,acquired_at=SYSTIMESTAMP,heartbeat_at=SYSTIMESTAMP,lease_expires_at=SYSTIMESTAMP+NUMTODSINTERVAL(:leaseSeconds,'SECOND'),updated_at=SYSTIMESTAMP WHERE lock_id=1`, operation, { autoCommit: false }); await connection.commit(); return operation; } finally { if (connection) try { await connection.close(); } catch (_) {} } }
async function updateOperation(patch = {}) { if (!patch.leaseToken) return null; let connection; try { connection = await db.getConnection(); const binds = { leaseToken: patch.leaseToken, status: patch.status ?? null, message: patch.message ?? null, progress: patch.progress ?? null, leaseSeconds: LEASE_SECONDS }; const result = await connection.execute(`UPDATE app_dataset_operation_lock SET status=COALESCE(:status,status),message=COALESCE(:message,message),progress=COALESCE(:progress,progress),heartbeat_at=SYSTIMESTAMP,lease_expires_at=SYSTIMESTAMP+NUMTODSINTERVAL(:leaseSeconds,'SECOND'),updated_at=SYSTIMESTAMP WHERE lock_id=1 AND lease_token=:leaseToken AND lease_expires_at>SYSTIMESTAMP`, binds, { autoCommit: false }); await connection.commit(); return result.rowsAffected || 0; } finally { if (connection) try { await connection.close(); } catch (_) {} } }
async function endOperation({ leaseToken, jobId = null } = {}) { if (!leaseToken) return null; let connection; try { connection = await db.getConnection(); const result = await connection.execute(`UPDATE app_dataset_operation_lock SET lease_token=NULL,owner_job_id=NULL,operation_kind=NULL,status=NULL,message=NULL,progress=NULL,acquired_at=NULL,heartbeat_at=NULL,lease_expires_at=NULL,updated_at=SYSTIMESTAMP WHERE lock_id=1 AND lease_token=:leaseToken AND (:jobId IS NULL OR owner_job_id=:jobId)`, { leaseToken, jobId }, { autoCommit: false }); await connection.commit(); return result.rowsAffected || 0; } finally { if (connection) try { await connection.close(); } catch (_) {} } }
module.exports = { beginOperation, updateOperation, endOperation, getActiveOperation };
