const crypto = require('crypto');
const db = require('../config/database');
const { readStoredState, saveDatasetStateOnConnection } = require('./datasetStateStore');
const PENDING = "'admitted','applying','ready','recovering'";
const generationId = () => `gen_${Date.now().toString(36)}_${crypto.randomUUID().slice(0, 8)}`;
async function admitGeneration({ jobId, initiatingActor, source }) { let connection; try { connection = await db.getConnection(); const prior = await readStoredState(connection); const id = generationId(); await connection.execute(`INSERT INTO app_dataset_generations (generation_id,job_id,initiating_actor,prior_generation_id,status,recovery_json,created_at,updated_at) VALUES (:generationId,:jobId,:actor,:priorGenerationId,'admitted',:recovery,SYSTIMESTAMP,SYSTIMESTAMP)`, { generationId: id, jobId, actor: initiatingActor, priorGenerationId: prior?.generationId || null, recovery: JSON.stringify({ source, priorGenerationId: prior?.generationId || null }) }, { autoCommit: false }); await connection.commit(); return { generationId: id, priorGenerationId: prior?.generationId || null, status: 'admitted' }; } finally { if (connection) try { await connection.close(); } catch (_) {} } }
async function markGeneration(generationIdValue, status, recovery = null) { let connection; try { connection = await db.getConnection(); await connection.execute(`UPDATE app_dataset_generations SET status=:status,recovery_json=COALESCE(TO_CLOB(:recovery),recovery_json),updated_at=SYSTIMESTAMP WHERE generation_id=:generationId`, { generationId: generationIdValue, status, recovery: recovery ? JSON.stringify(recovery) : null }, { autoCommit: false }); await connection.commit(); } finally { if (connection) try { await connection.close(); } catch (_) {} } }
async function stageGenerationSnapshot(generationIdValue, snapshot) { let connection; try { connection = await db.getConnection(); await connection.execute(`UPDATE app_dataset_generations SET rollback_dataset_json=:snapshot,status='applying',updated_at=SYSTIMESTAMP WHERE generation_id=:generationId AND status='admitted'`, { generationId: generationIdValue, snapshot: JSON.stringify(snapshot) }, { autoCommit: false }); await connection.commit(); } finally { if (connection) try { await connection.close(); } catch (_) {} } }
async function recordFeatureEvidence(generationIdValue, evidence) { let connection; try { connection = await db.getConnection(); await connection.execute(`UPDATE app_dataset_generations SET required_features_json=:evidence,updated_at=SYSTIMESTAMP WHERE generation_id=:generationId`, { generationId: generationIdValue, evidence: JSON.stringify(evidence) }, { autoCommit: false }); await connection.commit(); } finally { if (connection) try { await connection.close(); } catch (_) {} } }
async function activateGeneration({ generationId, source, label, version }) { let connection; try { connection = await db.getConnection(); await saveDatasetStateOnConnection(connection, { source, label, version, generationId }); await connection.execute(`UPDATE app_dataset_generations SET status='active',activated_at=SYSTIMESTAMP,updated_at=SYSTIMESTAMP WHERE generation_id=:generationId AND status='ready'`, { generationId }, { autoCommit: false }); await connection.execute(`UPDATE app_dataset_generations SET status='rolled_back',updated_at=SYSTIMESTAMP WHERE generation_id<>:generationId AND status='active'`, { generationId }, { autoCommit: false }); await connection.commit(); } finally { if (connection) try { await connection.close(); } catch (_) {} } }
async function readPendingGeneration() { let connection; try { connection = await db.getConnection(); const result = await connection.execute(`SELECT generation_id,job_id,status FROM app_dataset_generations WHERE status IN (${PENDING}) ORDER BY created_at FETCH FIRST 1 ROW ONLY`); return result.rows[0] || null; } finally { if (connection) try { await connection.close(); } catch (_) {} } }
async function listInterruptedGenerations() { let connection; try { connection = await db.getConnection(); const result = await connection.execute(`SELECT generation_id,job_id,initiating_actor,status,rollback_dataset_json FROM app_dataset_generations WHERE status IN (${PENDING}) ORDER BY created_at`); return result.rows || []; } finally { if (connection) try { await connection.close(); } catch (_) {} } }
module.exports = { activateGeneration, admitGeneration, markGeneration, readPendingGeneration, stageGenerationSnapshot, recordFeatureEvidence, listInterruptedGenerations };
